-- ════════════════════════════════════════════════════════════════
-- Bootstrap complet — projet Supabase DEV (base vide)
-- ════════════════════════════════════════════════════════════════
--
-- CONTEXTE
-- La base de prod n'a pas de schéma SQL versionné (les tables ont
-- été créées au fil de l'eau via le dashboard). Ce script reconstruit
-- l'intégralité du schéma (tables + RLS + fonctions) à partir de la
-- lecture du code frontend (src/hooks/*.ts, src/types/*.ts,
-- src/contexts/AuthContext.tsx) et des migrations déjà écrites
-- (0001 à 0005), pour un NOUVEAU projet Supabase vide dédié au dev.
--
-- COMMENT L'UTILISER
-- 1. Crée un nouveau projet Supabase (ex: "dimos-poboard-dev").
-- 2. Colle l'intégralité de ce fichier dans son SQL Editor et exécute.
-- 3. Storage → vérifie que le bucket "avatars" est bien créé et public.
-- 4. Récupère son URL + anon key (Settings → API) pour ton .env local.
-- 5. (Optionnel) Déploie la fonction Edge "invite-user" sur ce projet
--    si tu veux tester l'invitation d'utilisateurs en dev :
--      npx supabase functions deploy invite-user --project-ref <ref-dev>
--
-- ⚠️ Ce script n'a pas été exécuté contre un vrai projet — vérifie
-- qu'il tourne sans erreur avant de t'en servir au quotidien. Il
-- démarre une base VIDE (aucune donnée) : normal, c'est voulu pour
-- un environnement de dev propre, séparé des vraies données prod.
-- ════════════════════════════════════════════════════════════════


-- ──────────────────────────────────────────────────────────────
-- 1. Tables
-- ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS produits (
  id                    bigint generated by default as identity primary key,
  nom                   text NOT NULL,
  description           text,
  couleur               text,
  actif                 boolean NOT NULL DEFAULT true,
  is_template           boolean NOT NULL DEFAULT false,
  created_at            timestamptz NOT NULL DEFAULT now(),
  vision                text,
  objectifs_q1          text,
  objectifs_q2          text,
  objectifs_q3          text,
  objectifs_q4          text,
  budget_etp            numeric,
  budget_invest         numeric,
  budget_achats         numeric,
  date_lancement_cible  date,
  priorite_strategique  integer,
  niveau_risque         text,
  kpis_cibles           text,
  outcome_estime        text,
  theme                 text,
  objectifs_trimestriels jsonb,
  risques               jsonb,
  actions_lop           jsonb,
  rag_config            jsonb
);

CREATE TABLE IF NOT EXISTS equipes (
  id          bigint generated by default as identity primary key,
  nom         text NOT NULL,
  description text,
  couleur     text,
  actif       boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id      uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text,
  role_global  text CHECK (role_global IS NULL OR role_global = 'admin'),
  trigramme    text,
  prenom       text,
  nom          text,
  role_metier  text,
  couleur      text,
  actif        boolean NOT NULL DEFAULT true,
  equipe_id    bigint REFERENCES equipes(id) ON DELETE SET NULL,
  equipe_ids   bigint[] NOT NULL DEFAULT '{}',
  avatar_url   text
);

CREATE TABLE IF NOT EXISTS user_produit_roles (
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  role       text NOT NULL CHECK (role IN ('po', 'dev', 'lecteur')),
  PRIMARY KEY (user_id, produit_id)
);

CREATE TABLE IF NOT EXISTS pending_profiles (
  id                     bigint generated by default as identity primary key,
  display_name           text NOT NULL,
  trigramme              text,
  prenom                 text,
  nom                    text,
  couleur                text,
  role_global            text CHECK (role_global IS NULL OR role_global = 'admin'),
  equipe_ids             bigint[] NOT NULL DEFAULT '{}',
  pending_produit_ids    bigint[] NOT NULL DEFAULT '{}',
  pending_produit_roles  jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS taches (
  id                bigint generated by default as identity primary key,
  id_tache          text NOT NULL UNIQUE,
  produit_id        bigint REFERENCES produits(id) ON DELETE CASCADE,
  epic              text NOT NULL,
  titre             text NOT NULL,
  type_fonction     text,
  description       text,
  criteres          text,
  lien_dod          text,
  commentaire       text,
  jalon             text,
  sprint_debut      text,
  sprint_fin        text,
  sprint            text,
  iteration         integer NOT NULL DEFAULT 1,
  moscow            text,
  priorite          text,
  statut            text NOT NULL DEFAULT 'À faire',
  effort_j          numeric NOT NULL DEFAULT 0,
  effort_realise_j  numeric,
  equipe            text,
  metier            text,
  assigne_a         text,
  type_tache        text,
  parent_id         text,
  famille_id        text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz
);

CREATE TABLE IF NOT EXISTS sprints (
  id          bigint generated by default as identity primary key,
  produit_id  bigint REFERENCES produits(id) ON DELETE CASCADE,
  numero      text NOT NULL,
  statut      text NOT NULL DEFAULT 'planifie',
  objectifs   text,
  review      text,
  started_at  timestamptz,
  closed_at   timestamptz,
  est_actif   boolean NOT NULL DEFAULT false,
  stats       jsonb,
  UNIQUE (numero, produit_id)
);

CREATE TABLE IF NOT EXISTS dod (
  id          bigint generated by default as identity primary key,
  produit_id  bigint REFERENCES produits(id) ON DELETE CASCADE,
  code        text NOT NULL,
  titre       text NOT NULL,
  description text,
  categorie   text,
  actif       boolean NOT NULL DEFAULT true,
  ordre       integer NOT NULL DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now(),
  UNIQUE (produit_id, code)
);

CREATE TABLE IF NOT EXISTS periodes_fermeture (
  id         bigint generated by default as identity primary key,
  annee      integer NOT NULL,
  label      text NOT NULL,
  date_debut date NOT NULL,
  date_fin   date NOT NULL
);

CREATE TABLE IF NOT EXISTS reunions (
  id           bigint generated by default as identity primary key,
  semaine      integer NOT NULL,
  annee        integer NOT NULL,
  animateur    text,
  notes_seance text,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (semaine, annee)
);

CREATE TABLE IF NOT EXISTS reunion_revues (
  id              bigint generated by default as identity primary key,
  reunion_id      bigint NOT NULL REFERENCES reunions(id) ON DELETE CASCADE,
  produit_id      bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  statut_presente text,
  blocages        integer NOT NULL DEFAULT 0,
  notes           text
);

CREATE TABLE IF NOT EXISTS reunion_sujets (
  id         bigint generated by default as identity primary key,
  reunion_id bigint NOT NULL REFERENCES reunions(id) ON DELETE CASCADE,
  type_tag   text,
  titre      text NOT NULL
);

CREATE TABLE IF NOT EXISTS finance_config (
  id             bigint PRIMARY KEY DEFAULT 1,
  jours_par_trim integer NOT NULL DEFAULT 65,
  equipe_tjms    jsonb NOT NULL DEFAULT '[]'::jsonb,
  trimestres     jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at     timestamptz
);

CREATE TABLE IF NOT EXISTS plan_charges (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  produit_id     bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  epic           text NOT NULL,
  assigne_a      text NOT NULL,
  semaine        integer NOT NULL,
  annee          integer NOT NULL,
  jours          numeric NOT NULL DEFAULT 0,
  jours_realises numeric NOT NULL DEFAULT 0,
  UNIQUE (produit_id, epic, assigne_a, semaine, annee)
);

CREATE TABLE IF NOT EXISTS app_settings (
  id                 bigint PRIMARY KEY DEFAULT 1,
  rag_config_default jsonb
);

CREATE TABLE IF NOT EXISTS quick_notes (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  text       text NOT NULL,
  done       boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS quick_notes_user_id_idx ON quick_notes(user_id);

CREATE TABLE IF NOT EXISTS dod_categories (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  nom        text NOT NULL,
  ordre      integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (produit_id, nom)
);
CREATE INDEX IF NOT EXISTS dod_categories_produit_id_idx ON dod_categories(produit_id);


-- ──────────────────────────────────────────────────────────────
-- 2. Fonctions utilitaires RLS (identiques à 0001_enable_rls.sql)
-- ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
  SELECT EXISTS (SELECT 1 FROM user_profiles WHERE user_id = auth.uid() AND role_global = 'admin');
$$;

CREATE OR REPLACE FUNCTION has_produit_role(p_produit_id bigint, p_roles text[])
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
  SELECT is_admin() OR EXISTS (
    SELECT 1 FROM user_produit_roles
    WHERE user_id = auth.uid() AND produit_id = p_produit_id AND role = ANY (p_roles)
  );
$$;

CREATE OR REPLACE FUNCTION has_any_produit_role(p_roles text[])
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
  SELECT is_admin() OR EXISTS (
    SELECT 1 FROM user_produit_roles WHERE user_id = auth.uid() AND role = ANY (p_roles)
  );
$$;

CREATE OR REPLACE FUNCTION can_edit(p_produit_id bigint)
RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT has_produit_role(p_produit_id, ARRAY['po']); $$;

CREATE OR REPLACE FUNCTION can_write(p_produit_id bigint)
RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT has_produit_role(p_produit_id, ARRAY['po', 'dev']); $$;

CREATE OR REPLACE FUNCTION has_any_role_on_produit(p_produit_id bigint)
RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT has_produit_role(p_produit_id, ARRAY['po', 'dev', 'lecteur']); $$;

-- RPC utilisée par useUpdatePendingProfile (contourne le cache de
-- schéma PostgREST juste après une modif de colonnes)
CREATE OR REPLACE FUNCTION update_pending_profile_data(p_id bigint, p_data jsonb)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  UPDATE pending_profiles SET
    display_name          = COALESCE(p_data->>'display_name', display_name),
    trigramme              = CASE WHEN p_data ? 'trigramme' THEN p_data->>'trigramme' ELSE trigramme END,
    prenom                 = CASE WHEN p_data ? 'prenom' THEN p_data->>'prenom' ELSE prenom END,
    nom                    = CASE WHEN p_data ? 'nom' THEN p_data->>'nom' ELSE nom END,
    couleur                = CASE WHEN p_data ? 'couleur' THEN p_data->>'couleur' ELSE couleur END,
    role_global            = CASE WHEN p_data ? 'role_global' THEN p_data->>'role_global' ELSE role_global END,
    equipe_ids             = CASE WHEN p_data ? 'equipe_ids' THEN ARRAY(SELECT jsonb_array_elements_text(p_data->'equipe_ids'))::bigint[] ELSE equipe_ids END,
    pending_produit_ids    = CASE WHEN p_data ? 'pending_produit_ids' THEN ARRAY(SELECT jsonb_array_elements_text(p_data->'pending_produit_ids'))::bigint[] ELSE pending_produit_ids END,
    pending_produit_roles  = CASE WHEN p_data ? 'pending_produit_roles' THEN p_data->'pending_produit_roles' ELSE pending_produit_roles END
  WHERE id = p_id;
END;
$$;


-- ──────────────────────────────────────────────────────────────
-- 3. RLS — mêmes règles que 0001_enable_rls.sql + 0002 (app_settings)
--    + 0003 (quick_notes) + 0005 (dod_categories)
-- ──────────────────────────────────────────────────────────────

ALTER TABLE produits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "produits_select" ON produits FOR SELECT TO authenticated USING (is_admin() OR has_any_role_on_produit(id));
CREATE POLICY "produits_insert" ON produits FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "produits_update" ON produits FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "produits_delete" ON produits FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE taches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "taches_select" ON taches FOR SELECT TO authenticated USING (produit_id IS NULL OR has_any_role_on_produit(produit_id));
CREATE POLICY "taches_insert" ON taches FOR INSERT TO authenticated WITH CHECK (produit_id IS NOT NULL AND can_write(produit_id));
CREATE POLICY "taches_update" ON taches FOR UPDATE TO authenticated USING (produit_id IS NOT NULL AND can_write(produit_id)) WITH CHECK (produit_id IS NOT NULL AND can_write(produit_id));
CREATE POLICY "taches_delete" ON taches FOR DELETE TO authenticated USING (produit_id IS NOT NULL AND can_write(produit_id));

ALTER TABLE plan_charges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "plan_charges_select" ON plan_charges FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "plan_charges_insert" ON plan_charges FOR INSERT TO authenticated WITH CHECK (can_write(produit_id));
CREATE POLICY "plan_charges_update" ON plan_charges FOR UPDATE TO authenticated USING (can_write(produit_id)) WITH CHECK (can_write(produit_id));
CREATE POLICY "plan_charges_delete" ON plan_charges FOR DELETE TO authenticated USING (can_write(produit_id));

ALTER TABLE dod ENABLE ROW LEVEL SECURITY;
CREATE POLICY "dod_select" ON dod FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "dod_insert" ON dod FOR INSERT TO authenticated WITH CHECK (can_edit(produit_id));
CREATE POLICY "dod_update" ON dod FOR UPDATE TO authenticated USING (can_edit(produit_id)) WITH CHECK (can_edit(produit_id));
CREATE POLICY "dod_delete" ON dod FOR DELETE TO authenticated USING (can_edit(produit_id));

ALTER TABLE dod_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "dod_categories_select" ON dod_categories FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "dod_categories_insert" ON dod_categories FOR INSERT TO authenticated WITH CHECK (can_edit(produit_id));
CREATE POLICY "dod_categories_update" ON dod_categories FOR UPDATE TO authenticated USING (can_edit(produit_id)) WITH CHECK (can_edit(produit_id));
CREATE POLICY "dod_categories_delete" ON dod_categories FOR DELETE TO authenticated USING (can_edit(produit_id));

ALTER TABLE sprints ENABLE ROW LEVEL SECURITY;
CREATE POLICY "sprints_select" ON sprints FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "sprints_insert" ON sprints FOR INSERT TO authenticated WITH CHECK (can_edit(produit_id));
CREATE POLICY "sprints_update" ON sprints FOR UPDATE TO authenticated USING (can_edit(produit_id)) WITH CHECK (can_edit(produit_id));
CREATE POLICY "sprints_delete" ON sprints FOR DELETE TO authenticated USING (can_edit(produit_id));

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_profiles_select" ON user_profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "user_profiles_insert" ON user_profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id OR is_admin());
CREATE POLICY "user_profiles_update" ON user_profiles FOR UPDATE TO authenticated
  USING (auth.uid() = user_id OR is_admin())
  WITH CHECK (
    (auth.uid() = user_id AND (role_global IS NOT DISTINCT FROM (SELECT role_global FROM user_profiles WHERE user_id = auth.uid())))
    OR is_admin()
  );
CREATE POLICY "user_profiles_delete" ON user_profiles FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE user_produit_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_produit_roles_select" ON user_produit_roles FOR SELECT TO authenticated USING (true);
CREATE POLICY "user_produit_roles_insert" ON user_produit_roles FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "user_produit_roles_update" ON user_produit_roles FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "user_produit_roles_delete" ON user_produit_roles FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE pending_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "pending_profiles_all" ON pending_profiles FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

ALTER TABLE equipes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "equipes_select" ON equipes FOR SELECT TO authenticated USING (true);
CREATE POLICY "equipes_insert" ON equipes FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "equipes_update" ON equipes FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "equipes_delete" ON equipes FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE periodes_fermeture ENABLE ROW LEVEL SECURITY;
CREATE POLICY "periodes_fermeture_select" ON periodes_fermeture FOR SELECT TO authenticated USING (true);
CREATE POLICY "periodes_fermeture_insert" ON periodes_fermeture FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "periodes_fermeture_update" ON periodes_fermeture FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "periodes_fermeture_delete" ON periodes_fermeture FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE reunions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "reunions_select" ON reunions FOR SELECT TO authenticated USING (true);
CREATE POLICY "reunions_insert" ON reunions FOR INSERT TO authenticated WITH CHECK (has_any_produit_role(ARRAY['po', 'dev']));
CREATE POLICY "reunions_update" ON reunions FOR UPDATE TO authenticated USING (has_any_produit_role(ARRAY['po', 'dev'])) WITH CHECK (has_any_produit_role(ARRAY['po', 'dev']));
CREATE POLICY "reunions_delete" ON reunions FOR DELETE TO authenticated USING (has_any_produit_role(ARRAY['po', 'dev']));

ALTER TABLE reunion_revues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "reunion_revues_select" ON reunion_revues FOR SELECT TO authenticated USING (true);
CREATE POLICY "reunion_revues_insert" ON reunion_revues FOR INSERT TO authenticated WITH CHECK (can_write(produit_id));
CREATE POLICY "reunion_revues_update" ON reunion_revues FOR UPDATE TO authenticated USING (can_write(produit_id)) WITH CHECK (can_write(produit_id));
CREATE POLICY "reunion_revues_delete" ON reunion_revues FOR DELETE TO authenticated USING (can_write(produit_id));

ALTER TABLE reunion_sujets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "reunion_sujets_select" ON reunion_sujets FOR SELECT TO authenticated USING (true);
CREATE POLICY "reunion_sujets_insert" ON reunion_sujets FOR INSERT TO authenticated WITH CHECK (has_any_produit_role(ARRAY['po', 'dev']));
CREATE POLICY "reunion_sujets_update" ON reunion_sujets FOR UPDATE TO authenticated USING (has_any_produit_role(ARRAY['po', 'dev'])) WITH CHECK (has_any_produit_role(ARRAY['po', 'dev']));
CREATE POLICY "reunion_sujets_delete" ON reunion_sujets FOR DELETE TO authenticated USING (has_any_produit_role(ARRAY['po', 'dev']));

ALTER TABLE finance_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_config_select" ON finance_config FOR SELECT TO authenticated USING (true);
CREATE POLICY "finance_config_insert" ON finance_config FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "finance_config_update" ON finance_config FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "finance_config_delete" ON finance_config FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "app_settings_select" ON app_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "app_settings_insert" ON app_settings FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "app_settings_update" ON app_settings FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "app_settings_delete" ON app_settings FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE quick_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "quick_notes_select" ON quick_notes FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "quick_notes_insert" ON quick_notes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "quick_notes_update" ON quick_notes FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "quick_notes_delete" ON quick_notes FOR DELETE TO authenticated USING (auth.uid() = user_id);


-- ──────────────────────────────────────────────────────────────
-- 4. Storage — bucket "avatars" (public en lecture, upload par le
--    propriétaire uniquement)
-- ──────────────────────────────────────────────────────────────

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "avatars_public_read" ON storage.objects FOR SELECT
  USING (bucket_id = 'avatars');

CREATE POLICY "avatars_auth_upload" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "avatars_auth_update" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'avatars') WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "avatars_auth_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'avatars');


-- ──────────────────────────────────────────────────────────────
-- 5. Config par défaut (singletons requis par l'app)
-- ──────────────────────────────────────────────────────────────

INSERT INTO finance_config (id, jours_par_trim, equipe_tjms, trimestres, updated_at)
VALUES (1, 65, '[]', '[]', now())
ON CONFLICT (id) DO NOTHING;

INSERT INTO app_settings (id, rag_config_default)
VALUES (1, '{"avancement":{"amber":10,"red":25},"budget":{"amber":10,"red":20},"blocages":{"amber":1,"red":3}}')
ON CONFLICT (id) DO NOTHING;


-- ════════════════════════════════════════════════════════════════
-- FIN. Prochaine étape : crée ton premier compte via l'écran de
-- login de l'app (pointée sur ce projet dev), puis dans le SQL
-- Editor : passe-le admin avec
--   UPDATE user_profiles SET role_global = 'admin' WHERE user_id = '<ton-uuid>';
-- (trouvable dans Authentication → Users)
-- ════════════════════════════════════════════════════════════════
