-- ════════════════════════════════════════════════════════════════
-- Journal d'activité serveur + Dépendances entre tâches + Notifications
-- ════════════════════════════════════════════════════════════════
--
-- CONTEXTE — trois lacunes identifiées lors de l'audit du projet :
-- 1. Le journal d'activité (useActivity.ts) ne vivait qu'en
--    localStorage du navigateur : deux postes = deux historiques,
--    rien de consultable côté serveur ni par un admin. On le
--    remplace par une vraie table.
-- 2. Aucun lien « bloque / est bloquée par » entre deux tâches
--    distinctes n'existait — seulement `parent_id` (hiérarchie
--    sous-tâche) et le statut "Bloqué" (une étiquette, pas une
--    relation).
-- 3. Aucune notification au-delà des toasts de confirmation d'action
--    locale : personne n'était prévenu d'une assignation, d'une
--    clôture de sprint ou d'un blocage.
-- ════════════════════════════════════════════════════════════════


-- ──────────────────────────────────────────────────────────────
-- 1. activite — journal d'activité par produit
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS activite (
  id         bigint generated by default as identity primary key,
  produit_id bigint REFERENCES produits(id) ON DELETE CASCADE,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action     text NOT NULL CHECK (action IN ('create', 'update', 'delete', 'status')),
  target     text NOT NULL,
  title      text NOT NULL,
  field      text,
  old_value  text,
  new_value  text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS activite_produit_id_idx ON activite(produit_id);
CREATE INDEX IF NOT EXISTS activite_created_at_idx ON activite(created_at DESC);

ALTER TABLE activite ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "activite_select" ON activite;
CREATE POLICY "activite_select" ON activite FOR SELECT TO authenticated
  USING (has_any_role_on_produit(produit_id));

DROP POLICY IF EXISTS "activite_insert" ON activite;
CREATE POLICY "activite_insert" ON activite FOR INSERT TO authenticated
  WITH CHECK (can_write(produit_id));

-- Effacer l'historique reste réservé aux admins (c'est un journal
-- d'équipe partagé désormais, pas un gadget local par poste).
DROP POLICY IF EXISTS "activite_delete" ON activite;
CREATE POLICY "activite_delete" ON activite FOR DELETE TO authenticated
  USING (is_admin());


-- ──────────────────────────────────────────────────────────────
-- 2. tache_dependances — « bloque / est bloquée par »
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tache_dependances (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  bloque_id  text NOT NULL,   -- id_tache qui bloque
  bloquee_id text NOT NULL,   -- id_tache qui est bloquée
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (bloque_id, bloquee_id),
  CHECK (bloque_id <> bloquee_id)
);
CREATE INDEX IF NOT EXISTS tache_dependances_produit_id_idx ON tache_dependances(produit_id);
CREATE INDEX IF NOT EXISTS tache_dependances_bloque_idx    ON tache_dependances(bloque_id);
CREATE INDEX IF NOT EXISTS tache_dependances_bloquee_idx   ON tache_dependances(bloquee_id);

ALTER TABLE tache_dependances ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tache_dependances_select" ON tache_dependances;
CREATE POLICY "tache_dependances_select" ON tache_dependances FOR SELECT TO authenticated
  USING (has_any_role_on_produit(produit_id));

DROP POLICY IF EXISTS "tache_dependances_insert" ON tache_dependances;
CREATE POLICY "tache_dependances_insert" ON tache_dependances FOR INSERT TO authenticated
  WITH CHECK (can_write(produit_id));

DROP POLICY IF EXISTS "tache_dependances_delete" ON tache_dependances;
CREATE POLICY "tache_dependances_delete" ON tache_dependances FOR DELETE TO authenticated
  USING (can_write(produit_id));


-- ──────────────────────────────────────────────────────────────
-- 3. notifications — in-app, jamais insérées directement par un
--    client (aucune policy INSERT authenticated) : seules les
--    fonctions SECURITY DEFINER ci-dessous peuvent en créer, ce
--    qui empêche un utilisateur de fabriquer une fausse notif
--    pour quelqu'un d'autre.
-- ──────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS notifications (
  id         bigint generated by default as identity primary key,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  produit_id bigint REFERENCES produits(id) ON DELETE CASCADE,
  type       text NOT NULL CHECK (type IN ('assignation', 'sprint_cloture', 'tache_bloquee')),
  title      text NOT NULL,
  body       text,
  target     text,
  lu         boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS notifications_user_id_idx ON notifications(user_id, created_at DESC);

ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "notifications_select" ON notifications;
CREATE POLICY "notifications_select" ON notifications FOR SELECT TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "notifications_update" ON notifications;
CREATE POLICY "notifications_update" ON notifications FOR UPDATE TO authenticated
  USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "notifications_delete" ON notifications;
CREATE POLICY "notifications_delete" ON notifications FOR DELETE TO authenticated
  USING (auth.uid() = user_id);


-- Assignation : notifie l'utilisateur dont le trigramme correspond
-- à `taches.assigne_a`, sauf auto-assignation.
CREATE OR REPLACE FUNCTION notify_task_assignment()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_user_id uuid;
BEGIN
  IF NEW.assigne_a IS NULL OR NEW.produit_id IS NULL THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND NEW.assigne_a IS NOT DISTINCT FROM OLD.assigne_a THEN RETURN NEW; END IF;

  SELECT user_id INTO v_user_id FROM user_profiles WHERE trigramme = NEW.assigne_a LIMIT 1;
  IF v_user_id IS NULL OR v_user_id = auth.uid() THEN RETURN NEW; END IF;

  INSERT INTO notifications (user_id, produit_id, type, title, body, target)
  VALUES (v_user_id, NEW.produit_id, 'assignation', 'Nouvelle tâche assignée', NEW.titre, NEW.id_tache);
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_assignment ON taches;
CREATE TRIGGER trg_notify_assignment AFTER INSERT OR UPDATE OF assigne_a ON taches
FOR EACH ROW EXECUTE FUNCTION notify_task_assignment();


-- Sprint clôturé : notifie les PO/dev du produit (hors auteur du changement).
CREATE OR REPLACE FUNCTION notify_sprint_closed()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.statut = 'cloture' AND (TG_OP = 'INSERT' OR OLD.statut IS DISTINCT FROM 'cloture') THEN
    INSERT INTO notifications (user_id, produit_id, type, title, body, target)
    SELECT upr.user_id, NEW.produit_id, 'sprint_cloture', 'Sprint clôturé', 'Sprint ' || NEW.numero, NEW.numero
    FROM user_produit_roles upr
    WHERE upr.produit_id = NEW.produit_id AND upr.role IN ('po', 'dev') AND upr.user_id <> auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_sprint_closed ON sprints;
CREATE TRIGGER trg_notify_sprint_closed AFTER INSERT OR UPDATE OF statut ON sprints
FOR EACH ROW EXECUTE FUNCTION notify_sprint_closed();


-- Tâche bloquée : notifie les PO/dev du produit (hors auteur du changement).
CREATE OR REPLACE FUNCTION notify_task_blocked()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.statut = 'Bloqué' AND NEW.produit_id IS NOT NULL
     AND (TG_OP = 'INSERT' OR OLD.statut IS DISTINCT FROM 'Bloqué') THEN
    INSERT INTO notifications (user_id, produit_id, type, title, body, target)
    SELECT upr.user_id, NEW.produit_id, 'tache_bloquee', 'Tâche bloquée', NEW.titre, NEW.id_tache
    FROM user_produit_roles upr
    WHERE upr.produit_id = NEW.produit_id AND upr.role IN ('po', 'dev') AND upr.user_id <> auth.uid();
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_task_blocked ON taches;
CREATE TRIGGER trg_notify_task_blocked AFTER INSERT OR UPDATE OF statut ON taches
FOR EACH ROW EXECUTE FUNCTION notify_task_blocked();
