-- ════════════════════════════════════════════════════════════════
-- Fil de commentaires par tâche + notifications de mention
-- ════════════════════════════════════════════════════════════════
--
-- CONTEXTE — une tâche n'avait qu'un champ `commentaire` texte libre
-- (une seule valeur, écrasée à chaque modification), pas de fil de
-- discussion horodaté entre plusieurs personnes. On ajoute une vraie
-- table de commentaires, et une notification quand on mentionne
-- quelqu'un avec `@trigramme` dans un commentaire.
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS tache_commentaires (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  id_tache   text NOT NULL,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  texte      text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tache_commentaires_tache_idx ON tache_commentaires(produit_id, id_tache);

ALTER TABLE tache_commentaires ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tache_commentaires_select" ON tache_commentaires;
CREATE POLICY "tache_commentaires_select" ON tache_commentaires FOR SELECT TO authenticated
  USING (has_any_role_on_produit(produit_id));

DROP POLICY IF EXISTS "tache_commentaires_insert" ON tache_commentaires;
CREATE POLICY "tache_commentaires_insert" ON tache_commentaires FOR INSERT TO authenticated
  WITH CHECK (can_write(produit_id) AND user_id = auth.uid());

-- Suppression : l'auteur du commentaire, ou un admin/PO du produit.
DROP POLICY IF EXISTS "tache_commentaires_delete" ON tache_commentaires;
CREATE POLICY "tache_commentaires_delete" ON tache_commentaires FOR DELETE TO authenticated
  USING (user_id = auth.uid() OR can_edit(produit_id));


-- Élargit le type de notification pour couvrir les mentions.
ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check
  CHECK (type IN ('assignation', 'sprint_cloture', 'tache_bloquee', 'mention'));

-- Mention @trigramme dans un commentaire : notifie la personne visée
-- (hors auto-mention).
CREATE OR REPLACE FUNCTION notify_mentions()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_trigramme text;
  v_user_id   uuid;
BEGIN
  FOR v_trigramme IN
    SELECT DISTINCT (regexp_matches(NEW.texte, '@([A-Za-z0-9]{2,5})', 'g'))[1]
  LOOP
    SELECT user_id INTO v_user_id FROM user_profiles WHERE trigramme = v_trigramme LIMIT 1;
    IF v_user_id IS NOT NULL AND v_user_id <> auth.uid() THEN
      INSERT INTO notifications (user_id, produit_id, type, title, body, target)
      VALUES (v_user_id, NEW.produit_id, 'mention', 'Vous avez été mentionné', NEW.texte, NEW.id_tache);
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_mentions ON tache_commentaires;
CREATE TRIGGER trg_notify_mentions AFTER INSERT ON tache_commentaires
FOR EACH ROW EXECUTE FUNCTION notify_mentions();
