-- ════════════════════════════════════════════════════════════════
-- Pièces jointes sur les tâches
-- ════════════════════════════════════════════════════════════════
--
-- CONTEXTE — aucun moyen d'attacher un fichier (maquette, spec,
-- capture d'écran) à une tâche. Sur le même principe que le bucket
-- `avatars` déjà en place, mais privé (pas d'accès public) : chaque
-- fichier est stocké sous `<produit_id>/<id_tache>/<horodatage>_<nom>`,
-- ce qui permet aux policies de storage de vérifier le rôle sur le
-- produit directement depuis le chemin, sans requête supplémentaire.
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS tache_attachments (
  id           bigint generated by default as identity primary key,
  produit_id   bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  id_tache     text NOT NULL,
  storage_path text NOT NULL,
  file_name    text NOT NULL,
  file_size    bigint,
  mime_type    text,
  uploaded_by  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tache_attachments_tache_idx ON tache_attachments(produit_id, id_tache);

ALTER TABLE tache_attachments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tache_attachments_select" ON tache_attachments;
CREATE POLICY "tache_attachments_select" ON tache_attachments FOR SELECT TO authenticated
  USING (has_any_role_on_produit(produit_id));

DROP POLICY IF EXISTS "tache_attachments_insert" ON tache_attachments;
CREATE POLICY "tache_attachments_insert" ON tache_attachments FOR INSERT TO authenticated
  WITH CHECK (can_write(produit_id) AND uploaded_by = auth.uid());

DROP POLICY IF EXISTS "tache_attachments_delete" ON tache_attachments;
CREATE POLICY "tache_attachments_delete" ON tache_attachments FOR DELETE TO authenticated
  USING (uploaded_by = auth.uid() OR can_write(produit_id));


-- Bucket privé (pas de lecture publique, contrairement à "avatars")
INSERT INTO storage.buckets (id, name, public)
VALUES ('attachments', 'attachments', false)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "attachments_select" ON storage.objects;
CREATE POLICY "attachments_select" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'attachments' AND has_any_role_on_produit((split_part(name, '/', 1))::bigint));

DROP POLICY IF EXISTS "attachments_insert" ON storage.objects;
CREATE POLICY "attachments_insert" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'attachments' AND can_write((split_part(name, '/', 1))::bigint));

DROP POLICY IF EXISTS "attachments_delete" ON storage.objects;
CREATE POLICY "attachments_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'attachments' AND can_write((split_part(name, '/', 1))::bigint));
