-- ════════════════════════════════════════════════════════════════
-- Suivi du temps fin — timer + pointage journalier par tâche
-- ════════════════════════════════════════════════════════════════
--
-- CONTEXTE — le seul suivi d'effort existant est `effort_realise_j`,
-- un nombre de jours saisi une seule fois quand une tâche passe à
-- "Fait" (modale Sprint Board). Pas de granularité journalière, pas
-- de chronomètre. Cette table ajoute un journal d'entrées de temps
-- (une ligne = une session ou une saisie manuelle pour un jour donné),
-- complémentaire à `effort_realise_j` — elle ne le remplace pas,
-- pour ne pas casser le flux de clôture de sprint existant.
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS tache_temps (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  id_tache   text NOT NULL,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date       date NOT NULL DEFAULT current_date,
  minutes    integer NOT NULL CHECK (minutes > 0),
  note       text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tache_temps_tache_idx ON tache_temps(produit_id, id_tache);
CREATE INDEX IF NOT EXISTS tache_temps_user_date_idx ON tache_temps(user_id, date);

ALTER TABLE tache_temps ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tache_temps_select" ON tache_temps;
CREATE POLICY "tache_temps_select" ON tache_temps FOR SELECT TO authenticated
  USING (has_any_role_on_produit(produit_id));

DROP POLICY IF EXISTS "tache_temps_insert" ON tache_temps;
CREATE POLICY "tache_temps_insert" ON tache_temps FOR INSERT TO authenticated
  WITH CHECK (can_write(produit_id) AND user_id = auth.uid());

DROP POLICY IF EXISTS "tache_temps_update" ON tache_temps;
CREATE POLICY "tache_temps_update" ON tache_temps FOR UPDATE TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "tache_temps_delete" ON tache_temps;
CREATE POLICY "tache_temps_delete" ON tache_temps FOR DELETE TO authenticated
  USING (user_id = auth.uid() OR can_write(produit_id));
