-- ════════════════════════════════════════════════════════════════
-- 0018 — Canal de discussion par produit
-- ════════════════════════════════════════════════════════════════
-- Fil de messages ouvert à toute personne ayant un rôle sur le
-- produit (y compris lecteur, contrairement aux commentaires de
-- tâche qui exigent can_write) — pour échanger en dehors du contexte
-- d'une tâche précise. Table append-only, même famille que
-- tache_commentaires : mentions @trigramme notifiées à l'insertion.
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS produit_messages (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  texte      text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS produit_messages_produit_idx ON produit_messages(produit_id, created_at);

ALTER TABLE produit_messages ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "produit_messages_select" ON produit_messages;
CREATE POLICY "produit_messages_select" ON produit_messages FOR SELECT TO authenticated
  USING (has_any_role_on_produit(produit_id));

DROP POLICY IF EXISTS "produit_messages_insert" ON produit_messages;
CREATE POLICY "produit_messages_insert" ON produit_messages FOR INSERT TO authenticated
  WITH CHECK (has_any_role_on_produit(produit_id) AND user_id = auth.uid());

DROP POLICY IF EXISTS "produit_messages_delete" ON produit_messages;
CREATE POLICY "produit_messages_delete" ON produit_messages FOR DELETE TO authenticated
  USING (user_id = auth.uid() OR can_edit(produit_id));

ALTER TABLE notifications DROP CONSTRAINT IF EXISTS notifications_type_check;
ALTER TABLE notifications ADD CONSTRAINT notifications_type_check
  CHECK (type IN ('assignation', 'sprint_cloture', 'tache_bloquee', 'mention', 'acces_demande', 'mention_reunion', 'mention_discussion'));

CREATE OR REPLACE FUNCTION notify_mention_produit_message()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_trigramme text;
  v_user_id   uuid;
BEGIN
  FOR v_trigramme IN
    SELECT DISTINCT (regexp_matches(NEW.texte, '@([A-Za-z0-9]{2,5})', 'g'))[1]
  LOOP
    SELECT user_id INTO v_user_id FROM user_profiles WHERE trigramme = v_trigramme LIMIT 1;
    IF v_user_id IS NOT NULL AND v_user_id <> auth.uid() THEN
      INSERT INTO notifications (user_id, produit_id, type, title, body, target)
      VALUES (v_user_id, NEW.produit_id, 'mention_discussion', 'Mentionné dans la discussion produit', NEW.texte, NULL);
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_mention_produit_message ON produit_messages;
CREATE TRIGGER trg_notify_mention_produit_message AFTER INSERT ON produit_messages
FOR EACH ROW EXECUTE FUNCTION notify_mention_produit_message();
