-- ════════════════════════════════════════════════════════════════
-- 0020 — Réunions multi-types
-- ════════════════════════════════════════════════════════════════
-- La réunion PO hebdo devient le premier type d'une famille de
-- réunions : chaque type (PO, Avancement projet, COPIL…) assemble
-- des sections modulaires (revue produits, notes, actions,
-- décisions, risques…). Les réunions génériques sont datées et
-- éventuellement liées à un produit ; leur contenu de sections vit
-- dans reunions.sections_data (jsonb). Les réunions PO existantes
-- sont rattachées au type builtin 'po' et datées au lundi ISO de
-- leur semaine.
-- ════════════════════════════════════════════════════════════════

-- ── Types de réunion ─────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS reunion_types (
  id         bigint generated by default as identity primary key,
  nom        text NOT NULL,
  couleur    text NOT NULL DEFAULT '#4A4CC8',
  -- Sections modulaires rendues dans l'ordre (clés côté front :
  -- 'revue_produits' | 'notes' | 'actions' | 'decisions' | 'risques' | 'jalons')
  sections   jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- 'po' = page dédiée /reunions/po (timer, revues) ; NULL = page générique
  builtin    text,
  actif      boolean NOT NULL DEFAULT true,
  ordre      int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE reunion_types ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "reunion_types_select" ON reunion_types;
CREATE POLICY "reunion_types_select" ON reunion_types FOR SELECT TO authenticated
  USING (true);

DROP POLICY IF EXISTS "reunion_types_insert" ON reunion_types;
CREATE POLICY "reunion_types_insert" ON reunion_types FOR INSERT TO authenticated
  WITH CHECK (is_admin());

DROP POLICY IF EXISTS "reunion_types_update" ON reunion_types;
CREATE POLICY "reunion_types_update" ON reunion_types FOR UPDATE TO authenticated
  USING (is_admin());

DROP POLICY IF EXISTS "reunion_types_delete" ON reunion_types;
CREATE POLICY "reunion_types_delete" ON reunion_types FOR DELETE TO authenticated
  USING (is_admin());

-- Seed des trois types de départ (idempotent via builtin/nom)
INSERT INTO reunion_types (nom, couleur, sections, builtin, ordre)
SELECT 'Réunion PO', '#4A4CC8', '["revue_produits","notes"]'::jsonb, 'po', 0
WHERE NOT EXISTS (SELECT 1 FROM reunion_types WHERE builtin = 'po');

INSERT INTO reunion_types (nom, couleur, sections, builtin, ordre)
SELECT 'Avancement projet', '#00C896', '["jalons","risques","actions","notes"]'::jsonb, NULL, 1
WHERE NOT EXISTS (SELECT 1 FROM reunion_types WHERE nom = 'Avancement projet');

INSERT INTO reunion_types (nom, couleur, sections, builtin, ordre)
SELECT 'COPIL', '#EF4444', '["decisions","actions","notes"]'::jsonb, NULL, 2
WHERE NOT EXISTS (SELECT 1 FROM reunion_types WHERE nom = 'COPIL');

-- ── Colonnes génériques sur reunions ─────────────────────────────
ALTER TABLE reunions ADD COLUMN IF NOT EXISTS type_id       bigint REFERENCES reunion_types(id);
ALTER TABLE reunions ADD COLUMN IF NOT EXISTS titre         text;
ALTER TABLE reunions ADD COLUMN IF NOT EXISTS date_reunion  date;
ALTER TABLE reunions ADD COLUMN IF NOT EXISTS produit_id    bigint REFERENCES produits(id) ON DELETE SET NULL;
ALTER TABLE reunions ADD COLUMN IF NOT EXISTS participants  jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE reunions ADD COLUMN IF NOT EXISTS sections_data jsonb NOT NULL DEFAULT '{}'::jsonb;

-- Les réunions non-PO n'ont pas de semaine/année
ALTER TABLE reunions ALTER COLUMN semaine DROP NOT NULL;
ALTER TABLE reunions ALTER COLUMN annee   DROP NOT NULL;

-- Backfill : rattache l'existant au type PO, daté au lundi ISO de la semaine
UPDATE reunions
SET type_id = (SELECT id FROM reunion_types WHERE builtin = 'po'),
    date_reunion = to_date(annee::text || '-' || lpad(semaine::text, 2, '0'), 'IYYY-IW')
WHERE type_id IS NULL AND semaine IS NOT NULL AND annee IS NOT NULL;

CREATE INDEX IF NOT EXISTS reunions_date_idx ON reunions(date_reunion DESC);
CREATE INDEX IF NOT EXISTS reunions_type_idx ON reunions(type_id);

-- Compat : le flux PO existant upsert par (semaine, annee) sans connaître
-- type_id ni date_reunion — on les complète automatiquement à l'insertion.
CREATE OR REPLACE FUNCTION reunions_defaults()
RETURNS trigger LANGUAGE plpgsql SET search_path = public AS $$
BEGIN
  IF NEW.type_id IS NULL AND NEW.semaine IS NOT NULL AND NEW.annee IS NOT NULL THEN
    NEW.type_id := (SELECT id FROM reunion_types WHERE builtin = 'po');
  END IF;
  IF NEW.date_reunion IS NULL AND NEW.semaine IS NOT NULL AND NEW.annee IS NOT NULL THEN
    NEW.date_reunion := to_date(NEW.annee::text || '-' || lpad(NEW.semaine::text, 2, '0'), 'IYYY-IW');
  END IF;
  RETURN NEW;
END $$;

DROP TRIGGER IF EXISTS reunions_defaults_trg ON reunions;
CREATE TRIGGER reunions_defaults_trg BEFORE INSERT OR UPDATE ON reunions
  FOR EACH ROW EXECUTE FUNCTION reunions_defaults();
