-- ════════════════════════════════════════════════════════════════
-- 0022 — Vues personnelles du cockpit Portefeuille
-- ════════════════════════════════════════════════════════════════
-- Chaque utilisateur peut composer des vues nommées du dashboard
-- portefeuille : quels widgets, où, à quelle taille. Le layout suit
-- le format react-grid-layout : [{ i, x, y, w, h }] où `i` est la
-- clé du widget dans le registre front (cockpit/widgets.tsx).
-- Strictement personnel : RLS owner-only.
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS user_dashboard_views (
  id         bigint generated by default as identity primary key,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  nom        text NOT NULL,
  layout     jsonb NOT NULL DEFAULT '[]'::jsonb,
  ordre      int NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS user_dashboard_views_user_idx ON user_dashboard_views(user_id, ordre);

ALTER TABLE user_dashboard_views ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "user_dashboard_views_select" ON user_dashboard_views;
CREATE POLICY "user_dashboard_views_select" ON user_dashboard_views FOR SELECT TO authenticated
  USING (user_id = auth.uid());

DROP POLICY IF EXISTS "user_dashboard_views_insert" ON user_dashboard_views;
CREATE POLICY "user_dashboard_views_insert" ON user_dashboard_views FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "user_dashboard_views_update" ON user_dashboard_views;
CREATE POLICY "user_dashboard_views_update" ON user_dashboard_views FOR UPDATE TO authenticated
  USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());

DROP POLICY IF EXISTS "user_dashboard_views_delete" ON user_dashboard_views;
CREATE POLICY "user_dashboard_views_delete" ON user_dashboard_views FOR DELETE TO authenticated
  USING (user_id = auth.uid());
