-- ════════════════════════════════════════════════════════════════
-- 0024 — Absences individuelles (plan de charges)
-- ════════════════════════════════════════════════════════════════
-- Congés / absences par membre : décomptés de la capacité hebdo dans
-- le plan de charges (en plus des jours fériés et fermetures globales).
-- Clé par trigramme (comme plan_charges.assigne_a) pour couvrir aussi
-- les profils en attente. Une absence à cheval sur deux années se
-- saisit en deux lignes.
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS absences (
  id         bigint generated by default as identity primary key,
  trigramme  text NOT NULL,
  annee      int NOT NULL,
  label      text NOT NULL DEFAULT 'Congés',
  date_debut date NOT NULL,
  date_fin   date NOT NULL,
  created_by uuid REFERENCES auth.users(id) ON DELETE SET NULL DEFAULT auth.uid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT absences_dates_chk CHECK (date_fin >= date_debut)
);
CREATE INDEX IF NOT EXISTS absences_annee_idx ON absences(annee, trigramme);

ALTER TABLE absences ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "absences_select" ON absences;
CREATE POLICY "absences_select" ON absences FOR SELECT TO authenticated
  USING (true);

-- Écriture : admin, PO d'au moins un produit, ou le membre lui-même
DROP POLICY IF EXISTS "absences_insert" ON absences;
CREATE POLICY "absences_insert" ON absences FOR INSERT TO authenticated
  WITH CHECK (
    is_admin()
    OR has_any_produit_role(ARRAY['po'])
    OR EXISTS (SELECT 1 FROM user_profiles up WHERE up.user_id = auth.uid() AND up.trigramme = absences.trigramme)
  );

DROP POLICY IF EXISTS "absences_delete" ON absences;
CREATE POLICY "absences_delete" ON absences FOR DELETE TO authenticated
  USING (
    is_admin()
    OR has_any_produit_role(ARRAY['po'])
    OR created_by = auth.uid()
    OR EXISTS (SELECT 1 FROM user_profiles up WHERE up.user_id = auth.uid() AND up.trigramme = absences.trigramme)
  );
