-- Board "Fast Task" (onglet Tâches) : capture rapide de tâches façon
-- post-it sur un canvas pannable/zoomable (React Flow côté client), avec
-- regroupement dans des cadres nommés.
--
-- Un post-it = une vraie ligne dans `taches` (créée minimaliste, sans Epic —
-- à compléter plus tard) + une ligne `tache_postit` qui ne porte QUE la
-- présentation sur le board (position, couleur, groupe). Pas de FK dure vers
-- `taches.id_tache` : `id_tache` n'a pas de contrainte UNIQUE en base (voir
-- migration 0030) — même pattern texte libre que `tache_commentaires`/
-- `tache_dependances` (0007_activite_dependances_notifications.sql).
--
-- `postit_groups` = cadre nommé, redimensionnable/déplaçable en bloc ; un
-- post-it y est rattaché via `tache_postit.group_id` (ON DELETE SET NULL :
-- supprimer un groupe ne supprime jamais les post-it qu'il contenait).
CREATE TABLE IF NOT EXISTS postit_groups (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  nom        text NOT NULL,
  x          numeric NOT NULL DEFAULT 0,
  y          numeric NOT NULL DEFAULT 0,
  width      numeric NOT NULL DEFAULT 320,
  height     numeric NOT NULL DEFAULT 240,
  couleur    text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS postit_groups_produit_id_idx ON postit_groups(produit_id);

CREATE TABLE IF NOT EXISTS tache_postit (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  id_tache   text NOT NULL UNIQUE,
  group_id   bigint REFERENCES postit_groups(id) ON DELETE SET NULL,
  x          numeric NOT NULL DEFAULT 0,
  y          numeric NOT NULL DEFAULT 0,
  couleur    text NOT NULL DEFAULT '#FEF08A',
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tache_postit_produit_id_idx ON tache_postit(produit_id);
CREATE INDEX IF NOT EXISTS tache_postit_group_id_idx ON tache_postit(group_id);

-- RLS : même pattern que tache_dependances/tache_commentaires — lecture pour
-- tout rôle sur le produit, écriture réservée à ceux qui peuvent modifier
-- (can_write : po/dev/admin).
ALTER TABLE postit_groups ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "postit_groups_select" ON postit_groups;
CREATE POLICY "postit_groups_select" ON postit_groups FOR SELECT TO authenticated
  USING (has_any_role_on_produit(produit_id));
DROP POLICY IF EXISTS "postit_groups_insert" ON postit_groups;
CREATE POLICY "postit_groups_insert" ON postit_groups FOR INSERT TO authenticated
  WITH CHECK (can_write(produit_id));
DROP POLICY IF EXISTS "postit_groups_update" ON postit_groups;
CREATE POLICY "postit_groups_update" ON postit_groups FOR UPDATE TO authenticated
  USING (can_write(produit_id)) WITH CHECK (can_write(produit_id));
DROP POLICY IF EXISTS "postit_groups_delete" ON postit_groups;
CREATE POLICY "postit_groups_delete" ON postit_groups FOR DELETE TO authenticated
  USING (can_write(produit_id));

ALTER TABLE tache_postit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tache_postit_select" ON tache_postit;
CREATE POLICY "tache_postit_select" ON tache_postit FOR SELECT TO authenticated
  USING (has_any_role_on_produit(produit_id));
DROP POLICY IF EXISTS "tache_postit_insert" ON tache_postit;
CREATE POLICY "tache_postit_insert" ON tache_postit FOR INSERT TO authenticated
  WITH CHECK (can_write(produit_id));
DROP POLICY IF EXISTS "tache_postit_update" ON tache_postit;
CREATE POLICY "tache_postit_update" ON tache_postit FOR UPDATE TO authenticated
  USING (can_write(produit_id)) WITH CHECK (can_write(produit_id));
DROP POLICY IF EXISTS "tache_postit_delete" ON tache_postit;
CREATE POLICY "tache_postit_delete" ON tache_postit FOR DELETE TO authenticated
  USING (can_write(produit_id));
