-- Itérations de tâche : boucles de rework trackées (conception → commande →
-- essai → validation, répétées plusieurs fois lors d'un prototypage), sans
-- dupliquer la tâche ni se contenter d'un commentaire perdu dans
-- l'historique. Chaque itération porte son propre objectif, ses critères
-- d'acceptation, son effort/assigné/sprint et sa conclusion.
--
-- Pas de FK dure vers `taches.id_tache` (pas de contrainte UNIQUE dessus,
-- voir migration 0030) — même pattern texte libre que `tache_commentaires`/
-- `tache_dependances` (0007_activite_dependances_notifications.sql).
CREATE TABLE IF NOT EXISTS tache_iterations (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  id_tache   text NOT NULL,
  numero     integer NOT NULL,
  objectif   text,
  criteres   text,
  effort_j   numeric,
  assigne_a  text,
  sprint     text,
  statut     text NOT NULL DEFAULT 'À faire',
  resultat   text,
  created_at timestamptz NOT NULL DEFAULT now(),
  closed_at  timestamptz,
  UNIQUE (id_tache, numero)
);
CREATE INDEX IF NOT EXISTS tache_iterations_produit_id_idx ON tache_iterations(produit_id);
CREATE INDEX IF NOT EXISTS tache_iterations_id_tache_idx ON tache_iterations(id_tache);

-- RLS : même pattern que tache_commentaires/tache_dependances — lecture pour
-- tout rôle sur le produit, écriture réservée à ceux qui peuvent modifier.
ALTER TABLE tache_iterations ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "tache_iterations_select" ON tache_iterations;
CREATE POLICY "tache_iterations_select" ON tache_iterations FOR SELECT TO authenticated
  USING (has_any_role_on_produit(produit_id));
DROP POLICY IF EXISTS "tache_iterations_insert" ON tache_iterations;
CREATE POLICY "tache_iterations_insert" ON tache_iterations FOR INSERT TO authenticated
  WITH CHECK (can_write(produit_id));
DROP POLICY IF EXISTS "tache_iterations_update" ON tache_iterations;
CREATE POLICY "tache_iterations_update" ON tache_iterations FOR UPDATE TO authenticated
  USING (can_write(produit_id)) WITH CHECK (can_write(produit_id));
DROP POLICY IF EXISTS "tache_iterations_delete" ON tache_iterations;
CREATE POLICY "tache_iterations_delete" ON tache_iterations FOR DELETE TO authenticated
  USING (can_write(produit_id));
