-- Gammes de produits : regroupement transverse au-dessus des produits, pour
-- la roadmap multi-produits (Gamme > Produit > Trimestre). Table de
-- référence globale, même pattern que `equipes` (0011/dev_bootstrap) :
-- lecture ouverte à tout utilisateur authentifié, écriture réservée aux
-- admins.
CREATE TABLE IF NOT EXISTS gammes_produits (
  id         bigint generated by default as identity primary key,
  nom        text NOT NULL,
  couleur    text,
  ordre      integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE gammes_produits ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "gammes_produits_select" ON gammes_produits;
CREATE POLICY "gammes_produits_select" ON gammes_produits FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "gammes_produits_insert" ON gammes_produits;
CREATE POLICY "gammes_produits_insert" ON gammes_produits FOR INSERT TO authenticated WITH CHECK (is_admin());
DROP POLICY IF EXISTS "gammes_produits_update" ON gammes_produits;
CREATE POLICY "gammes_produits_update" ON gammes_produits FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
DROP POLICY IF EXISTS "gammes_produits_delete" ON gammes_produits;
CREATE POLICY "gammes_produits_delete" ON gammes_produits FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE produits ADD COLUMN IF NOT EXISTS gamme_id bigint REFERENCES gammes_produits(id) ON DELETE SET NULL;
