-- Éléments de la Roadmap : décorrélés de la table produits et de son
-- avancement. Un élément = un nom + une gamme + une période (trimestre
-- début/fin). Regroupement par gamme via gammes_produits (déjà existante),
-- sans plus aucun lien avec produits.gamme_id (conservée mais plus utilisée
-- par la Roadmap).

CREATE TABLE IF NOT EXISTS roadmap_items (
  id                  bigint generated by default as identity primary key,
  gamme_id            bigint NOT NULL REFERENCES gammes_produits(id) ON DELETE CASCADE,
  nom                 text NOT NULL,
  couleur             text,
  trimestre_debut     text NOT NULL,
  trimestre_fin       text NOT NULL,
  -- [{ trimestre: 'Q1-2026', objectifs: [{id,texte,checked}] }] — objectifs
  -- libres par trimestre couvert par l'élément, saisis depuis la roadmap.
  trimestre_objectifs jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- Icône lucide affichée sur la barre ('rocket', 'star', 'target', ...).
  icone               text,
  ordre               integer NOT NULL DEFAULT 0,
  created_at          timestamptz NOT NULL DEFAULT now()
);

-- Idempotence : ajoute les colonnes si la table a été créée par une version
-- antérieure de cette migration (CREATE TABLE IF NOT EXISTS ne les rajoute pas).
ALTER TABLE roadmap_items ADD COLUMN IF NOT EXISTS trimestre_objectifs jsonb NOT NULL DEFAULT '[]'::jsonb;
ALTER TABLE roadmap_items ADD COLUMN IF NOT EXISTS icone text;

ALTER TABLE roadmap_items ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "roadmap_items_select" ON roadmap_items;
DROP POLICY IF EXISTS "roadmap_items_insert" ON roadmap_items;
DROP POLICY IF EXISTS "roadmap_items_update" ON roadmap_items;
DROP POLICY IF EXISTS "roadmap_items_delete" ON roadmap_items;

CREATE POLICY "roadmap_items_select" ON roadmap_items FOR SELECT TO authenticated USING (true);
CREATE POLICY "roadmap_items_insert" ON roadmap_items FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "roadmap_items_update" ON roadmap_items FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "roadmap_items_delete" ON roadmap_items FOR DELETE TO authenticated USING (is_admin());
