-- ════════════════════════════════════════════════════════════════
-- 0061 — Scorecard portefeuille (incréments livrés par initiative)
-- ════════════════════════════════════════════════════════════════
-- Nouveau widget cockpit "Scorecard" (vue FL3) : suivi hebdomadaire
-- d'un nombre d'incréments livrés par initiative transverse (hors
-- produits D3X), avec objectif à date de deadline — remplace le
-- classeur Excel "SCORECARD DATA T3" tenu à la main chaque semaine.
-- Portefeuille, pas de produit_id : visible/éditable par toute
-- personne connectée (même logique que suggestions, cf. 0059).
-- ════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS scorecard_initiatives (
  id                  bigint generated by default as identity primary key,
  nom                 text NOT NULL,
  semaine_depart      smallint NOT NULL,
  semaine_deadline    smallint NOT NULL,
  objectif_increments int NOT NULL DEFAULT 0,
  couleur             text,
  ordre               int NOT NULL DEFAULT 0,
  created_by          uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at          timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS scorecard_initiatives_ordre_idx ON scorecard_initiatives(ordre);

-- Valeur CUMULATIVE d'incréments livrés à la semaine donnée (comme dans le
-- classeur d'origine) — une ligne par (initiative, semaine).
CREATE TABLE IF NOT EXISTS scorecard_increments (
  id            bigint generated by default as identity primary key,
  initiative_id bigint NOT NULL REFERENCES scorecard_initiatives(id) ON DELETE CASCADE,
  semaine       smallint NOT NULL,
  valeur        int NOT NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  UNIQUE (initiative_id, semaine)
);
CREATE INDEX IF NOT EXISTS scorecard_increments_initiative_idx ON scorecard_increments(initiative_id, semaine);

ALTER TABLE scorecard_initiatives ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "scorecard_initiatives_select" ON scorecard_initiatives;
CREATE POLICY "scorecard_initiatives_select" ON scorecard_initiatives FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "scorecard_initiatives_insert" ON scorecard_initiatives;
CREATE POLICY "scorecard_initiatives_insert" ON scorecard_initiatives FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "scorecard_initiatives_update" ON scorecard_initiatives;
CREATE POLICY "scorecard_initiatives_update" ON scorecard_initiatives FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "scorecard_initiatives_delete" ON scorecard_initiatives;
CREATE POLICY "scorecard_initiatives_delete" ON scorecard_initiatives FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE scorecard_increments ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "scorecard_increments_select" ON scorecard_increments;
CREATE POLICY "scorecard_increments_select" ON scorecard_increments FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "scorecard_increments_insert" ON scorecard_increments;
CREATE POLICY "scorecard_increments_insert" ON scorecard_increments FOR INSERT TO authenticated WITH CHECK (true);
DROP POLICY IF EXISTS "scorecard_increments_update" ON scorecard_increments;
CREATE POLICY "scorecard_increments_update" ON scorecard_increments FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "scorecard_increments_delete" ON scorecard_increments;
CREATE POLICY "scorecard_increments_delete" ON scorecard_increments FOR DELETE TO authenticated USING (true);

-- ── Import du classeur "SCORECARD DATA T3" (les 3 initiatives réelles ;
-- la ligne "TEST" du classeur était un exemple de calibration, pas une
-- vraie initiative — volontairement pas importée) ──────────────────
INSERT INTO scorecard_initiatives (nom, semaine_depart, semaine_deadline, objectif_increments, ordre) VALUES
  ('Dimax : nouveau process de vente',   26, 40, 264, 10),
  ('Diamant : nouveau process de vente', 26, 40, 150, 20),
  ('EOLE (230 k€)',                      26, 40, 50,  30)
ON CONFLICT DO NOTHING;

INSERT INTO scorecard_increments (initiative_id, semaine, valeur)
SELECT i.id, v.semaine, v.valeur
FROM scorecard_initiatives i
JOIN (VALUES
  ('Dimax : nouveau process de vente',   26, 0),
  ('Dimax : nouveau process de vente',   27, 0),
  ('Dimax : nouveau process de vente',   28, 0),
  ('Dimax : nouveau process de vente',   29, 0),
  ('Diamant : nouveau process de vente', 26, 1),
  ('Diamant : nouveau process de vente', 27, 8),
  ('Diamant : nouveau process de vente', 28, 11),
  ('Diamant : nouveau process de vente', 29, 19),
  ('EOLE (230 k€)',                      26, 1),
  ('EOLE (230 k€)',                      27, 2),
  ('EOLE (230 k€)',                      28, 3),
  ('EOLE (230 k€)',                      29, 3)
) AS v(nom, semaine, valeur) ON v.nom = i.nom
ON CONFLICT (initiative_id, semaine) DO NOTHING;
