-- ════════════════════════════════════════════════════════════════
-- Bootstrap complet — projet Supabase DEV (base vide)
-- ════════════════════════════════════════════════════════════════
--
-- CONTEXTE
-- La base de prod n'a pas de schéma SQL versionné (les tables ont
-- été créées au fil de l'eau via le dashboard). Ce script reconstruit
-- l'intégralité du schéma (tables + RLS + fonctions) à partir de la
-- lecture du code frontend (src/hooks/*.ts, src/types/*.ts,
-- src/contexts/AuthContext.tsx) et des migrations déjà écrites
-- (0001 à 0012), pour un NOUVEAU projet Supabase vide dédié au dev.
--
-- COMMENT L'UTILISER
-- 1. Crée un nouveau projet Supabase (ex: "dimos-poboard-dev").
-- 2. Colle l'intégralité de ce fichier dans son SQL Editor et exécute.
-- 3. Storage → vérifie que le bucket "avatars" est bien créé et public.
-- 4. Récupère son URL + anon key (Settings → API) pour ton .env local.
-- 5. (Optionnel) Déploie la fonction Edge "invite-user" sur ce projet
--    si tu veux tester l'invitation d'utilisateurs en dev :
--      npx supabase functions deploy invite-user --project-ref <ref-dev>
--
-- ⚠️ Ce script n'a pas été exécuté contre un vrai projet — vérifie
-- qu'il tourne sans erreur avant de t'en servir au quotidien. Il
-- démarre une base VIDE (aucune donnée) : normal, c'est voulu pour
-- un environnement de dev propre, séparé des vraies données prod.
-- ════════════════════════════════════════════════════════════════


-- ──────────────────────────────────────────────────────────────
-- 1. Tables
-- ──────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS produits (
  id                    bigint generated by default as identity primary key,
  nom                   text NOT NULL,
  description           text,
  couleur               text,
  actif                 boolean NOT NULL DEFAULT true,
  is_template           boolean NOT NULL DEFAULT false,
  created_at            timestamptz NOT NULL DEFAULT now(),
  vision                text,
  objectifs_q1          text,
  objectifs_q2          text,
  objectifs_q3          text,
  objectifs_q4          text,
  budget_etp            numeric,
  budget_invest         numeric,
  budget_achats         numeric,
  date_lancement_cible  date,
  priorite_strategique  integer,
  niveau_risque         text,
  kpis_cibles           text,
  outcome_estime        text,
  theme                 text,
  objectifs_trimestriels jsonb,
  risques               jsonb,
  actions_lop           jsonb,
  rag_config            jsonb,
  discussion_bg_url     text,
  discussion_bg_opacity numeric NOT NULL DEFAULT 0.15
);

CREATE TABLE IF NOT EXISTS equipes (
  id          bigint generated by default as identity primary key,
  nom         text NOT NULL,
  description text,
  couleur     text,
  actif       boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS user_profiles (
  user_id      uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  display_name text,
  role_global  text CHECK (role_global IS NULL OR role_global = 'admin'),
  trigramme    text,
  prenom       text,
  nom          text,
  role_metier  text,
  couleur      text,
  actif        boolean NOT NULL DEFAULT true,
  equipe_id    bigint REFERENCES equipes(id) ON DELETE SET NULL,
  equipe_ids   bigint[] NOT NULL DEFAULT '{}',
  avatar_url   text
);

CREATE TABLE IF NOT EXISTS user_produit_roles (
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  role       text NOT NULL CHECK (role IN ('po', 'dev', 'lecteur')),
  PRIMARY KEY (user_id, produit_id)
);

CREATE TABLE IF NOT EXISTS pending_profiles (
  id                     bigint generated by default as identity primary key,
  display_name           text NOT NULL,
  trigramme              text,
  prenom                 text,
  nom                    text,
  couleur                text,
  role_global            text CHECK (role_global IS NULL OR role_global = 'admin'),
  equipe_ids             bigint[] NOT NULL DEFAULT '{}',
  pending_produit_ids    bigint[] NOT NULL DEFAULT '{}',
  pending_produit_roles  jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS taches (
  id                bigint generated by default as identity primary key,
  id_tache          text NOT NULL UNIQUE,
  produit_id        bigint REFERENCES produits(id) ON DELETE CASCADE,
  epic              text NOT NULL,
  titre             text NOT NULL,
  type_fonction     text,
  description       text,
  criteres          text,
  lien_dod          text,
  commentaire       text,
  jalon             text,
  sprint_debut      text,
  sprint_fin        text,
  sprint            text,
  iteration         integer NOT NULL DEFAULT 1,
  moscow            text,
  priorite          text,
  statut            text NOT NULL DEFAULT 'À faire',
  effort_j          numeric NOT NULL DEFAULT 0,
  effort_realise_j  numeric,
  equipe            text,
  metier            text,
  assigne_a         text,
  type_tache        text,
  parent_id         text,
  famille_id        text,
  ordre_kanban      integer,
  ordre_backlog     integer,
  critere_lie_id    text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_at        timestamptz
);

CREATE TABLE IF NOT EXISTS sprints (
  id          bigint generated by default as identity primary key,
  produit_id  bigint REFERENCES produits(id) ON DELETE CASCADE,
  numero      text NOT NULL,
  statut      text NOT NULL DEFAULT 'planifie',
  objectifs   text,
  review      text,
  started_at  timestamptz,
  closed_at   timestamptz,
  est_actif   boolean NOT NULL DEFAULT false,
  stats       jsonb,
  UNIQUE (numero, produit_id)
);

-- "dod" est historique : la table sert de référentiel d'EXIGENCES produit
-- (fonctionnelles / performance / sécurité / coût), voir migration 0028.
CREATE TABLE IF NOT EXISTS dod (
  id               bigint generated by default as identity primary key,
  produit_id       bigint REFERENCES produits(id) ON DELETE CASCADE,
  code             text NOT NULL,
  titre            text NOT NULL,
  description      text,
  categorie        text,
  actif            boolean NOT NULL DEFAULT true,
  ordre            integer NOT NULL DEFAULT 0,
  type             text NOT NULL DEFAULT 'fonctionnelle',
  criticite        text NOT NULL DEFAULT 'moyenne',
  verifiee         boolean NOT NULL DEFAULT false,
  valeur_cible     text,
  valeur_constatee text,
  created_at       timestamptz NOT NULL DEFAULT now(),
  UNIQUE (produit_id, code)
);

CREATE TABLE IF NOT EXISTS periodes_fermeture (
  id         bigint generated by default as identity primary key,
  annee      integer NOT NULL,
  label      text NOT NULL,
  date_debut date NOT NULL,
  date_fin   date NOT NULL
);

CREATE TABLE IF NOT EXISTS reunions (
  id           bigint generated by default as identity primary key,
  semaine      integer NOT NULL,
  annee        integer NOT NULL,
  animateur    text,
  notes_seance text,
  phase_notes  jsonb NOT NULL DEFAULT '["","","",""]'::jsonb,
  created_at   timestamptz NOT NULL DEFAULT now(),
  UNIQUE (semaine, annee)
);

CREATE TABLE IF NOT EXISTS reunion_revues (
  id              bigint generated by default as identity primary key,
  reunion_id      bigint NOT NULL REFERENCES reunions(id) ON DELETE CASCADE,
  produit_id      bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  statut_presente text,
  blocages        integer NOT NULL DEFAULT 0,
  notes           text,
  UNIQUE (reunion_id, produit_id)
);

CREATE TABLE IF NOT EXISTS reunion_sujets (
  id         bigint generated by default as identity primary key,
  reunion_id bigint NOT NULL REFERENCES reunions(id) ON DELETE CASCADE,
  type_tag   text,
  titre      text NOT NULL
);

CREATE TABLE IF NOT EXISTS finance_config (
  id             bigint PRIMARY KEY DEFAULT 1,
  jours_par_trim integer NOT NULL DEFAULT 65,
  equipe_tjms    jsonb NOT NULL DEFAULT '[]'::jsonb,
  trimestres     jsonb NOT NULL DEFAULT '[]'::jsonb,
  updated_at     timestamptz
);

CREATE TABLE IF NOT EXISTS plan_charges (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  produit_id     bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  epic           text NOT NULL,
  assigne_a      text NOT NULL,
  semaine        integer NOT NULL,
  annee          integer NOT NULL,
  jours          numeric NOT NULL DEFAULT 0,
  jours_realises numeric NOT NULL DEFAULT 0,
  UNIQUE (produit_id, epic, assigne_a, semaine, annee)
);

CREATE TABLE IF NOT EXISTS app_settings (
  id                 bigint PRIMARY KEY DEFAULT 1,
  rag_config_default jsonb
);

CREATE TABLE IF NOT EXISTS quick_notes (
  id         uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  text       text NOT NULL,
  done       boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS quick_notes_user_id_idx ON quick_notes(user_id);

CREATE TABLE IF NOT EXISTS suggestions (
  id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  auteur_id   uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  titre       text NOT NULL,
  description text,
  statut      text NOT NULL DEFAULT 'nouvelle' CHECK (statut IN ('nouvelle', 'acceptee', 'rejetee', 'fermee')),
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz
);
CREATE INDEX IF NOT EXISTS suggestions_statut_idx ON suggestions(statut);

CREATE TABLE IF NOT EXISTS dod_categories (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  nom        text NOT NULL,
  ordre      integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (produit_id, nom)
);
CREATE INDEX IF NOT EXISTS dod_categories_produit_id_idx ON dod_categories(produit_id);

CREATE TABLE IF NOT EXISTS epics (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  code       text NOT NULL,
  nom        text NOT NULL,
  couleur    text DEFAULT '#5B21B6',
  bg_couleur text DEFAULT '#EDE9FE',
  ordre      integer DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS epics_produit_id_code_key ON epics(produit_id, code);

CREATE TABLE IF NOT EXISTS jalons (
  id          bigint generated by default as identity primary key,
  produit_id  bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  code        text NOT NULL,
  nom         text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  couleur     text DEFAULT '#5B21B6',
  ordre       integer DEFAULT 0,
  created_at  timestamptz NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX IF NOT EXISTS jalons_produit_id_code_key ON jalons(produit_id, code);
CREATE INDEX IF NOT EXISTS jalons_produit_id_idx ON jalons(produit_id);

CREATE TABLE IF NOT EXISTS activite (
  id         bigint generated by default as identity primary key,
  produit_id bigint REFERENCES produits(id) ON DELETE CASCADE,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  action     text NOT NULL CHECK (action IN ('create', 'update', 'delete', 'status')),
  target     text NOT NULL,
  title      text NOT NULL,
  field      text,
  old_value  text,
  new_value  text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS activite_produit_id_idx ON activite(produit_id);
CREATE INDEX IF NOT EXISTS activite_created_at_idx ON activite(created_at DESC);

CREATE TABLE IF NOT EXISTS tache_dependances (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  bloque_id  text NOT NULL,
  bloquee_id text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (bloque_id, bloquee_id),
  CHECK (bloque_id <> bloquee_id)
);
CREATE INDEX IF NOT EXISTS tache_dependances_produit_id_idx ON tache_dependances(produit_id);
CREATE INDEX IF NOT EXISTS tache_dependances_bloque_idx    ON tache_dependances(bloque_id);
CREATE INDEX IF NOT EXISTS tache_dependances_bloquee_idx   ON tache_dependances(bloquee_id);

CREATE TABLE IF NOT EXISTS notifications (
  id         bigint generated by default as identity primary key,
  user_id    uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  produit_id bigint REFERENCES produits(id) ON DELETE CASCADE,
  type       text NOT NULL CHECK (type IN ('assignation', 'sprint_cloture', 'tache_bloquee', 'mention', 'acces_demande', 'mention_reunion', 'mention_discussion')),
  title      text NOT NULL,
  body       text,
  target     text,
  lu         boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS notifications_user_id_idx ON notifications(user_id, created_at DESC);

CREATE TABLE IF NOT EXISTS tache_commentaires (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  id_tache   text NOT NULL,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  texte      text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tache_commentaires_tache_idx ON tache_commentaires(produit_id, id_tache);

CREATE TABLE IF NOT EXISTS produit_messages (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  texte      text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS produit_messages_produit_idx ON produit_messages(produit_id, created_at);

CREATE TABLE IF NOT EXISTS tache_attachments (
  id           bigint generated by default as identity primary key,
  produit_id   bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  id_tache     text NOT NULL,
  storage_path text NOT NULL,
  file_name    text NOT NULL,
  file_size    bigint,
  mime_type    text,
  uploaded_by  uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tache_attachments_tache_idx ON tache_attachments(produit_id, id_tache);

CREATE TABLE IF NOT EXISTS tache_temps (
  id         bigint generated by default as identity primary key,
  produit_id bigint NOT NULL REFERENCES produits(id) ON DELETE CASCADE,
  id_tache   text NOT NULL,
  user_id    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  date       date NOT NULL DEFAULT current_date,
  minutes    integer NOT NULL CHECK (minutes > 0),
  note       text,
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS tache_temps_tache_idx ON tache_temps(produit_id, id_tache);
CREATE INDEX IF NOT EXISTS tache_temps_user_date_idx ON tache_temps(user_id, date);


-- ──────────────────────────────────────────────────────────────
-- 2. Fonctions utilitaires RLS (identiques à 0001_enable_rls.sql)
-- ──────────────────────────────────────────────────────────────

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
  SELECT EXISTS (SELECT 1 FROM user_profiles WHERE user_id = auth.uid() AND role_global = 'admin');
$$;

CREATE OR REPLACE FUNCTION has_produit_role(p_produit_id bigint, p_roles text[])
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
  SELECT is_admin() OR EXISTS (
    SELECT 1 FROM user_produit_roles
    WHERE user_id = auth.uid() AND produit_id = p_produit_id AND role = ANY (p_roles)
  );
$$;

CREATE OR REPLACE FUNCTION has_any_produit_role(p_roles text[])
RETURNS boolean LANGUAGE sql SECURITY DEFINER SET search_path = public STABLE AS $$
  SELECT is_admin() OR EXISTS (
    SELECT 1 FROM user_produit_roles WHERE user_id = auth.uid() AND role = ANY (p_roles)
  );
$$;

CREATE OR REPLACE FUNCTION can_edit(p_produit_id bigint)
RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT has_produit_role(p_produit_id, ARRAY['po']); $$;

CREATE OR REPLACE FUNCTION can_write(p_produit_id bigint)
RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT has_produit_role(p_produit_id, ARRAY['po', 'dev']); $$;

CREATE OR REPLACE FUNCTION has_any_role_on_produit(p_produit_id bigint)
RETURNS boolean LANGUAGE sql STABLE AS $$ SELECT has_produit_role(p_produit_id, ARRAY['po', 'dev', 'lecteur']); $$;

-- RPC utilisée par useUpdatePendingProfile (contourne le cache de
-- schéma PostgREST juste après une modif de colonnes)
-- ⚠️ SECURITY DEFINER : garde-fou is_admin() obligatoire (0012), sinon
-- escalade de privilège via role_global.
CREATE OR REPLACE FUNCTION update_pending_profile_data(p_id bigint, p_data jsonb)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Accès refusé';
  END IF;

  UPDATE pending_profiles SET
    display_name          = COALESCE(p_data->>'display_name', display_name),
    trigramme              = CASE WHEN p_data ? 'trigramme' THEN p_data->>'trigramme' ELSE trigramme END,
    prenom                 = CASE WHEN p_data ? 'prenom' THEN p_data->>'prenom' ELSE prenom END,
    nom                    = CASE WHEN p_data ? 'nom' THEN p_data->>'nom' ELSE nom END,
    couleur                = CASE WHEN p_data ? 'couleur' THEN p_data->>'couleur' ELSE couleur END,
    role_global            = CASE WHEN p_data ? 'role_global' THEN p_data->>'role_global' ELSE role_global END,
    equipe_ids             = CASE WHEN p_data ? 'equipe_ids' THEN ARRAY(SELECT jsonb_array_elements_text(p_data->'equipe_ids'))::bigint[] ELSE equipe_ids END,
    pending_produit_ids    = CASE WHEN p_data ? 'pending_produit_ids' THEN ARRAY(SELECT jsonb_array_elements_text(p_data->'pending_produit_ids'))::bigint[] ELSE pending_produit_ids END,
    pending_produit_roles  = CASE WHEN p_data ? 'pending_produit_roles' THEN p_data->'pending_produit_roles' ELSE pending_produit_roles END
  WHERE id = p_id;
END;
$$;

-- Date de dernière connexion (auth.users, non exposé au client) pour Setup →
-- Équipes & Utilisateurs — garde-fou is_admin() obligatoire (0029).
CREATE OR REPLACE FUNCTION get_last_sign_in_dates()
RETURNS TABLE(user_id uuid, last_sign_in_at timestamptz)
LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT is_admin() THEN
    RAISE EXCEPTION 'Accès refusé';
  END IF;

  RETURN QUERY SELECT au.id, au.last_sign_in_at FROM auth.users au;
END;
$$;

-- RPC utilisée par le panneau "Points à traiter" pour envoyer une
-- quick note vers actions_lop d'un produit, sans ouvrir toute la
-- table produits en écriture aux PO/dev (voir 0006_action_lop_rpc.sql)
CREATE OR REPLACE FUNCTION add_action_lop(p_produit_id bigint, p_action jsonb)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NOT can_write(p_produit_id) THEN
    RAISE EXCEPTION 'Accès refusé';
  END IF;
  UPDATE produits
  SET actions_lop = COALESCE(actions_lop, '[]'::jsonb) || jsonb_build_array(p_action)
  WHERE id = p_produit_id;
END;
$$;


-- ──────────────────────────────────────────────────────────────
-- 3. RLS — mêmes règles que 0001_enable_rls.sql + 0002 (app_settings)
--    + 0003 (quick_notes) + 0005 (dod_categories)
-- ──────────────────────────────────────────────────────────────

ALTER TABLE produits ENABLE ROW LEVEL SECURITY;
CREATE POLICY "produits_select" ON produits FOR SELECT TO authenticated USING (is_admin() OR has_any_role_on_produit(id));
CREATE POLICY "produits_insert" ON produits FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "produits_update" ON produits FOR UPDATE TO authenticated USING (can_edit(id)) WITH CHECK (can_edit(id));
CREATE POLICY "produits_delete" ON produits FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE taches ENABLE ROW LEVEL SECURITY;
CREATE POLICY "taches_select" ON taches FOR SELECT TO authenticated USING (produit_id IS NULL OR has_any_role_on_produit(produit_id));
CREATE POLICY "taches_insert" ON taches FOR INSERT TO authenticated WITH CHECK (produit_id IS NOT NULL AND can_write(produit_id));
CREATE POLICY "taches_update" ON taches FOR UPDATE TO authenticated USING (produit_id IS NOT NULL AND can_write(produit_id)) WITH CHECK (produit_id IS NOT NULL AND can_write(produit_id));
CREATE POLICY "taches_delete" ON taches FOR DELETE TO authenticated USING (produit_id IS NOT NULL AND can_write(produit_id));

ALTER TABLE plan_charges ENABLE ROW LEVEL SECURITY;
CREATE POLICY "plan_charges_select" ON plan_charges FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "plan_charges_insert" ON plan_charges FOR INSERT TO authenticated WITH CHECK (can_write(produit_id));
CREATE POLICY "plan_charges_update" ON plan_charges FOR UPDATE TO authenticated USING (can_write(produit_id)) WITH CHECK (can_write(produit_id));
CREATE POLICY "plan_charges_delete" ON plan_charges FOR DELETE TO authenticated USING (can_write(produit_id));

ALTER TABLE dod ENABLE ROW LEVEL SECURITY;
CREATE POLICY "dod_select" ON dod FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "dod_insert" ON dod FOR INSERT TO authenticated WITH CHECK (can_edit(produit_id));
CREATE POLICY "dod_update" ON dod FOR UPDATE TO authenticated USING (can_edit(produit_id)) WITH CHECK (can_edit(produit_id));
CREATE POLICY "dod_delete" ON dod FOR DELETE TO authenticated USING (can_edit(produit_id));

ALTER TABLE dod_categories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "dod_categories_select" ON dod_categories FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "dod_categories_insert" ON dod_categories FOR INSERT TO authenticated WITH CHECK (can_edit(produit_id));
CREATE POLICY "dod_categories_update" ON dod_categories FOR UPDATE TO authenticated USING (can_edit(produit_id)) WITH CHECK (can_edit(produit_id));
CREATE POLICY "dod_categories_delete" ON dod_categories FOR DELETE TO authenticated USING (can_edit(produit_id));

ALTER TABLE epics ENABLE ROW LEVEL SECURITY;
CREATE POLICY "epics_select" ON epics FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "epics_insert" ON epics FOR INSERT TO authenticated WITH CHECK (can_edit(produit_id));
CREATE POLICY "epics_update" ON epics FOR UPDATE TO authenticated USING (can_edit(produit_id)) WITH CHECK (can_edit(produit_id));
CREATE POLICY "epics_delete" ON epics FOR DELETE TO authenticated USING (can_edit(produit_id));

ALTER TABLE jalons ENABLE ROW LEVEL SECURITY;
CREATE POLICY "jalons_select" ON jalons FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "jalons_insert" ON jalons FOR INSERT TO authenticated WITH CHECK (can_edit(produit_id));
CREATE POLICY "jalons_update" ON jalons FOR UPDATE TO authenticated USING (can_edit(produit_id)) WITH CHECK (can_edit(produit_id));
CREATE POLICY "jalons_delete" ON jalons FOR DELETE TO authenticated USING (can_edit(produit_id));

ALTER TABLE sprints ENABLE ROW LEVEL SECURITY;
CREATE POLICY "sprints_select" ON sprints FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "sprints_insert" ON sprints FOR INSERT TO authenticated WITH CHECK (can_edit(produit_id));
CREATE POLICY "sprints_update" ON sprints FOR UPDATE TO authenticated USING (can_edit(produit_id)) WITH CHECK (can_edit(produit_id));
CREATE POLICY "sprints_delete" ON sprints FOR DELETE TO authenticated USING (can_edit(produit_id));

ALTER TABLE user_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_profiles_select" ON user_profiles FOR SELECT TO authenticated USING (true);
CREATE POLICY "user_profiles_insert" ON user_profiles FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id OR is_admin());
CREATE POLICY "user_profiles_update" ON user_profiles FOR UPDATE TO authenticated
  USING (auth.uid() = user_id OR is_admin())
  WITH CHECK (
    (auth.uid() = user_id AND (role_global IS NOT DISTINCT FROM (SELECT role_global FROM user_profiles WHERE user_id = auth.uid())))
    OR is_admin()
  );
CREATE POLICY "user_profiles_delete" ON user_profiles FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE user_produit_roles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "user_produit_roles_select" ON user_produit_roles FOR SELECT TO authenticated USING (true);
CREATE POLICY "user_produit_roles_insert" ON user_produit_roles FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "user_produit_roles_update" ON user_produit_roles FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "user_produit_roles_delete" ON user_produit_roles FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE pending_profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY "pending_profiles_all" ON pending_profiles FOR ALL TO authenticated USING (is_admin()) WITH CHECK (is_admin());

ALTER TABLE equipes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "equipes_select" ON equipes FOR SELECT TO authenticated USING (true);
CREATE POLICY "equipes_insert" ON equipes FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "equipes_update" ON equipes FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "equipes_delete" ON equipes FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE periodes_fermeture ENABLE ROW LEVEL SECURITY;
CREATE POLICY "periodes_fermeture_select" ON periodes_fermeture FOR SELECT TO authenticated USING (true);
CREATE POLICY "periodes_fermeture_insert" ON periodes_fermeture FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "periodes_fermeture_update" ON periodes_fermeture FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "periodes_fermeture_delete" ON periodes_fermeture FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE reunions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "reunions_select" ON reunions FOR SELECT TO authenticated USING (true);
CREATE POLICY "reunions_insert" ON reunions FOR INSERT TO authenticated WITH CHECK (has_any_produit_role(ARRAY['po', 'dev']));
CREATE POLICY "reunions_update" ON reunions FOR UPDATE TO authenticated USING (has_any_produit_role(ARRAY['po', 'dev'])) WITH CHECK (has_any_produit_role(ARRAY['po', 'dev']));
CREATE POLICY "reunions_delete" ON reunions FOR DELETE TO authenticated USING (has_any_produit_role(ARRAY['po', 'dev']));

ALTER TABLE reunion_revues ENABLE ROW LEVEL SECURITY;
CREATE POLICY "reunion_revues_select" ON reunion_revues FOR SELECT TO authenticated USING (true);
CREATE POLICY "reunion_revues_insert" ON reunion_revues FOR INSERT TO authenticated WITH CHECK (can_write(produit_id));
CREATE POLICY "reunion_revues_update" ON reunion_revues FOR UPDATE TO authenticated USING (can_write(produit_id)) WITH CHECK (can_write(produit_id));
CREATE POLICY "reunion_revues_delete" ON reunion_revues FOR DELETE TO authenticated USING (can_write(produit_id));

ALTER TABLE reunion_sujets ENABLE ROW LEVEL SECURITY;
CREATE POLICY "reunion_sujets_select" ON reunion_sujets FOR SELECT TO authenticated USING (true);
CREATE POLICY "reunion_sujets_insert" ON reunion_sujets FOR INSERT TO authenticated WITH CHECK (has_any_produit_role(ARRAY['po', 'dev']));
CREATE POLICY "reunion_sujets_update" ON reunion_sujets FOR UPDATE TO authenticated USING (has_any_produit_role(ARRAY['po', 'dev'])) WITH CHECK (has_any_produit_role(ARRAY['po', 'dev']));
CREATE POLICY "reunion_sujets_delete" ON reunion_sujets FOR DELETE TO authenticated USING (has_any_produit_role(ARRAY['po', 'dev']));

ALTER TABLE finance_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY "finance_config_select" ON finance_config FOR SELECT TO authenticated USING (true);
CREATE POLICY "finance_config_insert" ON finance_config FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "finance_config_update" ON finance_config FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "finance_config_delete" ON finance_config FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "app_settings_select" ON app_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "app_settings_insert" ON app_settings FOR INSERT TO authenticated WITH CHECK (is_admin());
CREATE POLICY "app_settings_update" ON app_settings FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "app_settings_delete" ON app_settings FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE quick_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "quick_notes_select" ON quick_notes FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "quick_notes_insert" ON quick_notes FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
CREATE POLICY "quick_notes_update" ON quick_notes FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "quick_notes_delete" ON quick_notes FOR DELETE TO authenticated USING (auth.uid() = user_id);

ALTER TABLE suggestions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "suggestions_select" ON suggestions FOR SELECT TO authenticated USING (true);
CREATE POLICY "suggestions_insert" ON suggestions FOR INSERT TO authenticated WITH CHECK (auteur_id = auth.uid());
CREATE POLICY "suggestions_update" ON suggestions FOR UPDATE TO authenticated USING (is_admin()) WITH CHECK (is_admin());
CREATE POLICY "suggestions_delete" ON suggestions FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE activite ENABLE ROW LEVEL SECURITY;
CREATE POLICY "activite_select" ON activite FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "activite_insert" ON activite FOR INSERT TO authenticated WITH CHECK (can_write(produit_id));
CREATE POLICY "activite_delete" ON activite FOR DELETE TO authenticated USING (is_admin());

ALTER TABLE tache_dependances ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tache_dependances_select" ON tache_dependances FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "tache_dependances_insert" ON tache_dependances FOR INSERT TO authenticated WITH CHECK (can_write(produit_id));
CREATE POLICY "tache_dependances_delete" ON tache_dependances FOR DELETE TO authenticated USING (can_write(produit_id));

-- notifications : aucune policy INSERT authenticated — seules les fonctions
-- SECURITY DEFINER ci-dessous peuvent en créer (un client ne peut jamais
-- fabriquer une fausse notification pour un autre utilisateur).
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
CREATE POLICY "notifications_select" ON notifications FOR SELECT TO authenticated USING (auth.uid() = user_id);
CREATE POLICY "notifications_update" ON notifications FOR UPDATE TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
CREATE POLICY "notifications_delete" ON notifications FOR DELETE TO authenticated USING (auth.uid() = user_id);

-- Assignation : notifie l'utilisateur dont le trigramme correspond à
-- `taches.assigne_a`, sauf auto-assignation.
CREATE OR REPLACE FUNCTION notify_task_assignment()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_user_id uuid;
BEGIN
  IF NEW.assigne_a IS NULL OR NEW.produit_id IS NULL THEN RETURN NEW; END IF;
  IF TG_OP = 'UPDATE' AND NEW.assigne_a IS NOT DISTINCT FROM OLD.assigne_a THEN RETURN NEW; END IF;
  SELECT user_id INTO v_user_id FROM user_profiles WHERE trigramme = NEW.assigne_a LIMIT 1;
  IF v_user_id IS NULL OR v_user_id = auth.uid() THEN RETURN NEW; END IF;
  INSERT INTO notifications (user_id, produit_id, type, title, body, target)
  VALUES (v_user_id, NEW.produit_id, 'assignation', 'Nouvelle tâche assignée', NEW.titre, NEW.id_tache);
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_notify_assignment ON taches;
CREATE TRIGGER trg_notify_assignment AFTER INSERT OR UPDATE OF assigne_a ON taches
FOR EACH ROW EXECUTE FUNCTION notify_task_assignment();

-- Sprint clôturé : notifie les PO/dev du produit (hors auteur du changement).
CREATE OR REPLACE FUNCTION notify_sprint_closed()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.statut = 'cloture' AND (TG_OP = 'INSERT' OR OLD.statut IS DISTINCT FROM 'cloture') THEN
    INSERT INTO notifications (user_id, produit_id, type, title, body, target)
    SELECT upr.user_id, NEW.produit_id, 'sprint_cloture', 'Sprint clôturé', 'Sprint ' || NEW.numero, NEW.numero
    FROM user_produit_roles upr
    WHERE upr.produit_id = NEW.produit_id AND upr.role IN ('po', 'dev') AND upr.user_id <> auth.uid();
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_notify_sprint_closed ON sprints;
CREATE TRIGGER trg_notify_sprint_closed AFTER INSERT OR UPDATE OF statut ON sprints
FOR EACH ROW EXECUTE FUNCTION notify_sprint_closed();

-- Tâche bloquée : notifie les PO/dev du produit (hors auteur du changement).
CREATE OR REPLACE FUNCTION notify_task_blocked()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
BEGIN
  IF NEW.statut = 'Bloqué' AND NEW.produit_id IS NOT NULL
     AND (TG_OP = 'INSERT' OR OLD.statut IS DISTINCT FROM 'Bloqué') THEN
    INSERT INTO notifications (user_id, produit_id, type, title, body, target)
    SELECT upr.user_id, NEW.produit_id, 'tache_bloquee', 'Tâche bloquée', NEW.titre, NEW.id_tache
    FROM user_produit_roles upr
    WHERE upr.produit_id = NEW.produit_id AND upr.role IN ('po', 'dev') AND upr.user_id <> auth.uid();
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_notify_task_blocked ON taches;
CREATE TRIGGER trg_notify_task_blocked AFTER INSERT OR UPDATE OF statut ON taches
FOR EACH ROW EXECUTE FUNCTION notify_task_blocked();

ALTER TABLE tache_commentaires ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tache_commentaires_select" ON tache_commentaires FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "tache_commentaires_insert" ON tache_commentaires FOR INSERT TO authenticated WITH CHECK (can_write(produit_id) AND user_id = auth.uid());
CREATE POLICY "tache_commentaires_delete" ON tache_commentaires FOR DELETE TO authenticated USING (user_id = auth.uid() OR can_edit(produit_id));

ALTER TABLE produit_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "produit_messages_select" ON produit_messages FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "produit_messages_insert" ON produit_messages FOR INSERT TO authenticated WITH CHECK (has_any_role_on_produit(produit_id) AND user_id = auth.uid());
CREATE POLICY "produit_messages_delete" ON produit_messages FOR DELETE TO authenticated USING (user_id = auth.uid() OR can_edit(produit_id));

-- Mention @trigramme dans un message du canal de discussion produit.
CREATE OR REPLACE FUNCTION notify_mention_produit_message()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_trigramme text;
  v_user_id   uuid;
BEGIN
  FOR v_trigramme IN
    SELECT DISTINCT (regexp_matches(NEW.texte, '@([A-Za-z0-9]{2,5})', 'g'))[1]
  LOOP
    SELECT user_id INTO v_user_id FROM user_profiles WHERE trigramme = v_trigramme LIMIT 1;
    IF v_user_id IS NOT NULL AND v_user_id <> auth.uid() THEN
      INSERT INTO notifications (user_id, produit_id, type, title, body, target)
      VALUES (v_user_id, NEW.produit_id, 'mention_discussion', 'Mentionné dans la discussion produit', NEW.texte, NULL);
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_notify_mention_produit_message ON produit_messages;
CREATE TRIGGER trg_notify_mention_produit_message AFTER INSERT ON produit_messages
FOR EACH ROW EXECUTE FUNCTION notify_mention_produit_message();

ALTER TABLE tache_attachments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tache_attachments_select" ON tache_attachments FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "tache_attachments_insert" ON tache_attachments FOR INSERT TO authenticated WITH CHECK (can_write(produit_id) AND uploaded_by = auth.uid());
CREATE POLICY "tache_attachments_delete" ON tache_attachments FOR DELETE TO authenticated USING (uploaded_by = auth.uid() OR can_write(produit_id));

ALTER TABLE tache_temps ENABLE ROW LEVEL SECURITY;
CREATE POLICY "tache_temps_select" ON tache_temps FOR SELECT TO authenticated USING (has_any_role_on_produit(produit_id));
CREATE POLICY "tache_temps_insert" ON tache_temps FOR INSERT TO authenticated WITH CHECK (can_write(produit_id) AND user_id = auth.uid());
CREATE POLICY "tache_temps_update" ON tache_temps FOR UPDATE TO authenticated USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid() AND can_write(produit_id));
CREATE POLICY "tache_temps_delete" ON tache_temps FOR DELETE TO authenticated USING (user_id = auth.uid() OR can_write(produit_id));

-- Mention @trigramme dans un commentaire : notifie la personne visée (hors auto-mention).
CREATE OR REPLACE FUNCTION notify_mentions()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_trigramme text;
  v_user_id   uuid;
BEGIN
  FOR v_trigramme IN
    SELECT DISTINCT (regexp_matches(NEW.texte, '@([A-Za-z0-9]{2,5})', 'g'))[1]
  LOOP
    SELECT user_id INTO v_user_id FROM user_profiles WHERE trigramme = v_trigramme LIMIT 1;
    IF v_user_id IS NOT NULL AND v_user_id <> auth.uid() THEN
      INSERT INTO notifications (user_id, produit_id, type, title, body, target)
      VALUES (v_user_id, NEW.produit_id, 'mention', 'Vous avez été mentionné', NEW.texte, NEW.id_tache);
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_notify_mentions ON tache_commentaires;
CREATE TRIGGER trg_notify_mentions AFTER INSERT ON tache_commentaires
FOR EACH ROW EXECUTE FUNCTION notify_mentions();

-- Demande d'accès à un produit (écran d'accueil sans accès) : notifie
-- les PO du produit visé + les admins globaux.
CREATE OR REPLACE FUNCTION request_produit_access(p_produit_id bigint, p_message text DEFAULT NULL)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_requester_name text;
  v_produit_nom    text;
  v_target uuid;
BEGIN
  IF auth.uid() IS NULL THEN
    RAISE EXCEPTION 'Authentification requise';
  END IF;

  SELECT COALESCE(display_name, 'Un utilisateur') INTO v_requester_name
  FROM user_profiles WHERE user_id = auth.uid();

  SELECT nom INTO v_produit_nom FROM produits WHERE id = p_produit_id;
  IF v_produit_nom IS NULL THEN
    RAISE EXCEPTION 'Produit introuvable';
  END IF;

  FOR v_target IN
    SELECT user_id FROM user_produit_roles WHERE produit_id = p_produit_id AND role = 'po'
    UNION
    SELECT user_id FROM user_profiles WHERE role_global = 'admin'
  LOOP
    IF v_target <> auth.uid() THEN
      INSERT INTO notifications (user_id, produit_id, type, title, body, target)
      VALUES (v_target, p_produit_id, 'acces_demande',
        'Demande d''accès — ' || v_produit_nom,
        v_requester_name || ' demande un accès à ce produit.' || COALESCE(' ' || NULLIF(trim(p_message), ''), ''),
        NULL);
    END IF;
  END LOOP;
END;
$$;

-- Mentions @trigramme dans les champs modifiables (pas un journal
-- d'entrées comme tache_commentaires) : on ne notifie que les
-- mentions nouvellement ajoutées, via un diff ancien/nouveau texte.
CREATE OR REPLACE FUNCTION extract_mentions(txt text)
RETURNS text[] LANGUAGE sql IMMUTABLE AS $$
  SELECT COALESCE(array_agg(DISTINCT m[1]), '{}')
  FROM regexp_matches(COALESCE(txt, ''), '@([A-Za-z0-9]{2,5})', 'g') AS m
$$;

CREATE OR REPLACE FUNCTION notify_mention_commentaire_tache()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_new_mentions text[];
  v_trigramme text;
  v_user_id uuid;
BEGIN
  IF NEW.produit_id IS NULL THEN RETURN NEW; END IF;
  v_new_mentions := ARRAY(
    SELECT unnest(extract_mentions(NEW.commentaire))
    EXCEPT SELECT unnest(extract_mentions(OLD.commentaire))
  );
  FOREACH v_trigramme IN ARRAY v_new_mentions LOOP
    SELECT user_id INTO v_user_id FROM user_profiles WHERE trigramme = v_trigramme LIMIT 1;
    IF v_user_id IS NOT NULL AND v_user_id <> auth.uid() THEN
      INSERT INTO notifications (user_id, produit_id, type, title, body, target)
      VALUES (v_user_id, NEW.produit_id, 'mention', 'Vous avez été mentionné', NEW.titre, NEW.id_tache);
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_mention_commentaire_tache ON taches;
CREATE TRIGGER trg_notify_mention_commentaire_tache AFTER UPDATE OF commentaire ON taches
FOR EACH ROW WHEN (NEW.commentaire IS DISTINCT FROM OLD.commentaire)
EXECUTE FUNCTION notify_mention_commentaire_tache();

CREATE OR REPLACE FUNCTION notify_mention_reunion_notes()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_old_text text;
  v_new_text text;
  v_new_mentions text[];
  v_trigramme text;
  v_user_id uuid;
  v_target text;
BEGIN
  v_old_text := COALESCE(OLD.notes_seance, '') || ' ' ||
    COALESCE((SELECT string_agg(x, ' ') FROM jsonb_array_elements_text(OLD.phase_notes) x), '');
  v_new_text := COALESCE(NEW.notes_seance, '') || ' ' ||
    COALESCE((SELECT string_agg(x, ' ') FROM jsonb_array_elements_text(NEW.phase_notes) x), '');
  v_new_mentions := ARRAY(SELECT unnest(extract_mentions(v_new_text)) EXCEPT SELECT unnest(extract_mentions(v_old_text)));
  v_target := NEW.semaine::text || '-' || NEW.annee::text;
  FOREACH v_trigramme IN ARRAY v_new_mentions LOOP
    SELECT user_id INTO v_user_id FROM user_profiles WHERE trigramme = v_trigramme LIMIT 1;
    IF v_user_id IS NOT NULL AND v_user_id <> auth.uid() THEN
      INSERT INTO notifications (user_id, produit_id, type, title, body, target)
      VALUES (v_user_id, NULL, 'mention_reunion', 'Mentionné en réunion PO', 'Semaine ' || NEW.semaine || '/' || NEW.annee, v_target);
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_mention_reunion_notes ON reunions;
CREATE TRIGGER trg_notify_mention_reunion_notes AFTER UPDATE ON reunions
FOR EACH ROW WHEN (NEW.notes_seance IS DISTINCT FROM OLD.notes_seance OR NEW.phase_notes IS DISTINCT FROM OLD.phase_notes)
EXECUTE FUNCTION notify_mention_reunion_notes();

CREATE OR REPLACE FUNCTION notify_mention_reunion_revue()
RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path = public AS $$
DECLARE
  v_old_text text := CASE WHEN TG_OP = 'UPDATE' THEN COALESCE(OLD.notes, '') ELSE '' END;
  v_new_mentions text[];
  v_trigramme text;
  v_user_id uuid;
  v_semaine int;
  v_annee int;
BEGIN
  IF TG_OP = 'UPDATE' AND NEW.notes IS NOT DISTINCT FROM OLD.notes THEN RETURN NEW; END IF;
  v_new_mentions := ARRAY(SELECT unnest(extract_mentions(NEW.notes)) EXCEPT SELECT unnest(extract_mentions(v_old_text)));
  IF array_length(v_new_mentions, 1) IS NULL THEN RETURN NEW; END IF;

  SELECT semaine, annee INTO v_semaine, v_annee FROM reunions WHERE id = NEW.reunion_id;

  FOREACH v_trigramme IN ARRAY v_new_mentions LOOP
    SELECT user_id INTO v_user_id FROM user_profiles WHERE trigramme = v_trigramme LIMIT 1;
    IF v_user_id IS NOT NULL AND v_user_id <> auth.uid() THEN
      INSERT INTO notifications (user_id, produit_id, type, title, body, target)
      VALUES (v_user_id, NEW.produit_id, 'mention_reunion', 'Mentionné en réunion PO',
        'Semaine ' || v_semaine || '/' || v_annee, v_semaine::text || '-' || v_annee::text);
    END IF;
  END LOOP;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_mention_reunion_revue ON reunion_revues;
CREATE TRIGGER trg_notify_mention_reunion_revue AFTER INSERT OR UPDATE OF notes ON reunion_revues
FOR EACH ROW EXECUTE FUNCTION notify_mention_reunion_revue();


-- ──────────────────────────────────────────────────────────────
-- 4. Storage — bucket "avatars" (public en lecture, upload par le
--    propriétaire uniquement)
-- ──────────────────────────────────────────────────────────────

INSERT INTO storage.buckets (id, name, public)
VALUES ('avatars', 'avatars', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "avatars_public_read" ON storage.objects FOR SELECT
  USING (bucket_id = 'avatars');

CREATE POLICY "avatars_auth_upload" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "avatars_auth_update" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'avatars') WITH CHECK (bucket_id = 'avatars');

CREATE POLICY "avatars_auth_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'avatars');

-- Bucket "discussion-backgrounds" — public en lecture, upload réservé admin
-- (fond personnalisable du canal de discussion produit).
INSERT INTO storage.buckets (id, name, public)
VALUES ('discussion-backgrounds', 'discussion-backgrounds', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "discussion_bg_public_read" ON storage.objects FOR SELECT
  USING (bucket_id = 'discussion-backgrounds');

CREATE POLICY "discussion_bg_admin_upload" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'discussion-backgrounds' AND is_admin());

CREATE POLICY "discussion_bg_admin_update" ON storage.objects FOR UPDATE TO authenticated
  USING (bucket_id = 'discussion-backgrounds' AND is_admin())
  WITH CHECK (bucket_id = 'discussion-backgrounds' AND is_admin());

CREATE POLICY "discussion_bg_admin_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'discussion-backgrounds' AND is_admin());

-- Bucket "attachments" — privé (contrairement à avatars) : chaque objet est
-- stocké sous "<produit_id>/<id_tache>/...", ce qui permet aux policies de
-- vérifier le rôle sur le produit directement depuis le chemin.
INSERT INTO storage.buckets (id, name, public)
VALUES ('attachments', 'attachments', false)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "attachments_select" ON storage.objects FOR SELECT TO authenticated
  USING (bucket_id = 'attachments' AND has_any_role_on_produit((split_part(name, '/', 1))::bigint));

CREATE POLICY "attachments_insert" ON storage.objects FOR INSERT TO authenticated
  WITH CHECK (bucket_id = 'attachments' AND can_write((split_part(name, '/', 1))::bigint));

CREATE POLICY "attachments_delete" ON storage.objects FOR DELETE TO authenticated
  USING (bucket_id = 'attachments' AND can_write((split_part(name, '/', 1))::bigint));


-- ──────────────────────────────────────────────────────────────
-- 5. Config par défaut (singletons requis par l'app)
-- ──────────────────────────────────────────────────────────────

INSERT INTO finance_config (id, jours_par_trim, equipe_tjms, trimestres, updated_at)
VALUES (1, 65, '[]', '[]', now())
ON CONFLICT (id) DO NOTHING;

INSERT INTO app_settings (id, rag_config_default)
VALUES (1, '{"avancement":{"amber":10,"red":25},"budget":{"amber":10,"red":20},"blocages":{"amber":1,"red":3}}')
ON CONFLICT (id) DO NOTHING;


-- ════════════════════════════════════════════════════════════════
-- FIN. Prochaine étape : crée ton premier compte via l'écran de
-- login de l'app (pointée sur ce projet dev), puis dans le SQL
-- Editor : passe-le admin avec
--   UPDATE user_profiles SET role_global = 'admin' WHERE user_id = '<ton-uuid>';
-- (trouvable dans Authentication → Users)
-- ════════════════════════════════════════════════════════════════
